#!/usr/bin/env python3
"""Extract each item layer from the .psb levels into trimmed PNGs and emit
levels-data.js. o1..o10 = odds, r* = reals, the bg layer is ignored."""
import os, re, glob, json
from psd_tools import PSDImage
from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))
LEVELS_DIR = os.path.join(ROOT, "levels")

# Every .psb in levels/ is its own level (plain + "Sticker" variants are distinct).
def themes():
    out = []
    for path in sorted(glob.glob(os.path.join(LEVELS_DIR, "*.psb"))):
        fn = os.path.basename(path)
        display = os.path.splitext(fn)[0]                 # "3D Beach Sticker"
        folder = re.sub(r'\s+', '_', display)             # "3D_Beach_Sticker"
        out.append((fn, folder, display))
    return out

def num(s):
    m = re.search(r'\d+', s)
    return int(m.group()) if m else 0

def trim(im):
    """Crop fully-transparent margins."""
    if im.mode != "RGBA":
        im = im.convert("RGBA")
    bbox = im.getchannel("A").getbbox()
    return im.crop(bbox) if bbox else im

def extract_theme(psb_name, folder, display):
    psd = PSDImage.open(os.path.join(LEVELS_DIR, psb_name))
    odd_dir = os.path.join(LEVELS_DIR, folder, "Odd")
    real_dir = os.path.join(LEVELS_DIR, folder, "Real")
    os.makedirs(odd_dir, exist_ok=True)
    os.makedirs(real_dir, exist_ok=True)

    odds, reals = {}, {}
    def walk(layers):
        for l in layers:
            nm = l.name.strip()
            is_odd = re.fullmatch(r'o\d+', nm)
            is_real = re.fullmatch(r'r\d+', nm)
            if (is_odd or is_real) and not l.is_group():
                try:
                    img = l.composite()
                except Exception as e:
                    print(f"   !! {psb_name}:{nm} composite failed: {e}")
                    img = None
                if img is not None:
                    img = trim(img)
                    if is_odd:  odds[nm] = img
                    else:       reals[nm] = img
            if l.is_group():
                walk(l)
    walk(psd)

    odd_paths, real_paths = [], []
    for nm in sorted(odds, key=num):
        p = f"Odd/{nm}.png"
        odds[nm].save(os.path.join(odd_dir, f"{nm}.png"))
        odd_paths.append(f"levels/{folder}/{p}")
    for nm in sorted(reals, key=num):
        p = f"Real/{nm}.png"
        reals[nm].save(os.path.join(real_dir, f"{nm}.png"))
        real_paths.append(f"levels/{folder}/{p}")

    print(f"  {display}: {len(odd_paths)} odds, {len(real_paths)} reals")
    return {"name": display, "odds": odd_paths, "reals": real_paths}

def build_sports():
    base = os.path.join(LEVELS_DIR, "Sports")
    odds = sorted(glob.glob(os.path.join(base, "Fake", "*.png")))
    reals = sorted(glob.glob(os.path.join(base, "Real", "*.png")),
                   key=lambda p: num(os.path.basename(p)))
    rel = lambda p: os.path.relpath(p, ROOT).replace(os.sep, "/")
    print(f"  Sports: {len(odds)} odds, {len(reals)} reals")
    return {"name": "Sports", "odds": [rel(p) for p in odds], "reals": [rel(p) for p in reals]}

def main():
    levels = [build_sports()]
    for psb, folder, display in themes():
        levels.append(extract_theme(psb, folder, display))

    out = os.path.join(ROOT, "levels-data.js")
    with open(out, "w") as fh:
        fh.write("// Auto-generated by extract_levels.py — do not edit by hand.\n")
        fh.write("window.LEVELS = " + json.dumps(levels, indent=2) + ";\n")
    print(f"\nWrote {out} with {len(levels)} levels.")

if __name__ == "__main__":
    main()
