// Pixhaku — üç öğreticiye eklenen 97 level. tools/build_pack.js üretir; kaynak: tools/pack_4-23.js ve tools/puzzles_100/.
// Pixhaku_prototype.html'deki levels dizisine eklenecek biçimde.
//   solution  mantıksal çözüm sırasında: Hint her zaman sıradaki kesinleşen parçayı verir.
//   artImage  üretilmiş görselin proje içindeki yolu; prototipte görsel dosyanın içine gömülür.
const PIXHAKU_LEVELS_4_100 = [
  {
    // Level 3 — Ayçiçeği Değirmeni · easy (17) · Mantığa alışma
    id: "sunflower-mill",
    order: 3,
    rows: 6,
    cols: 6,
    clues: [
      { r: 2, c: 0, n: 6 },
      { r: 3, c: 3, n: 12 },
      { r: 3, c: 5, n: 8 },
      { r: 4, c: 0, n: 4 },
      { r: 5, c: 5, n: 4 },
      { r: 5, c: 0, n: 2 }
    ],
    solution: [
      [5, 0, 5, 1],
      [0, 4, 3, 5],
      [4, 4, 5, 5],
      [0, 2, 5, 3],
      [3, 0, 4, 1],
      [0, 0, 2, 1]
    ],
    artName: "Sunflower Mill",
    artImage: "assets/levels/sunflower-mill.jpg",
    difficulty: 17,
    tag: "easy",
    artPrompt: "Cozy pixel-art sunflower mill scene built on the Level 3 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 4 — Lavanta Evi · easy (18) · Mantığa alışma
    id: "lavender-cottage",
    order: 4,
    rows: 7,
    cols: 6,
    clues: [
      { r: 1, c: 0, n: 5 },
      { r: 0, c: 5, n: 10 },
      { r: 3, c: 2, n: 12 },
      { r: 4, c: 5, n: 5 },
      { r: 6, c: 1, n: 6 },
      { r: 6, c: 4, n: 4 }
    ],
    solution: [
      [0, 1, 1, 5],
      [0, 0, 4, 0],
      [2, 5, 6, 5],
      [5, 0, 6, 2],
      [2, 1, 4, 4],
      [5, 3, 6, 4]
    ],
    artName: "Lavender Cottage",
    artImage: "assets/levels/lavender-cottage-6x7.jpg",
    difficulty: 18,
    tag: "easy",
    artPrompt: "Cozy pixel-art lavender cottage scene built on the Level 4 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 6 — Elma Bahçesi · easy (19) · Mantığa alışma
    id: "apple-orchard",
    order: 6,
    rows: 6,
    cols: 5,
    clues: [
      { r: 0, c: 1, n: 6 },
      { r: 2, c: 2, n: 9 },
      { r: 4, c: 0, n: 8 },
      { r: 4, c: 4, n: 2 },
      { r: 5, c: 2, n: 3 },
      { r: 5, c: 4, n: 2 }
    ],
    solution: [
      [5, 3, 5, 4],
      [0, 2, 2, 4],
      [3, 4, 4, 4],
      [0, 0, 2, 1],
      [3, 0, 4, 3],
      [5, 0, 5, 2]
    ],
    artName: "Apple Orchard",
    artImage: "assets/levels/apple-orchard-5x6.jpg",
    difficulty: 19,
    tag: "easy",
    artPrompt: "Cozy pixel-art apple orchard scene built on the Level 6 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 7 — Ördek Göleti · easy (20) · Mantığa alışma
    id: "duck-pond",
    order: 7,
    rows: 6,
    cols: 6,
    clues: [
      { r: 1, c: 2, n: 10 },
      { r: 1, c: 5, n: 3 },
      { r: 3, c: 0, n: 8 },
      { r: 4, c: 4, n: 4 },
      { r: 5, c: 5, n: 3 },
      { r: 5, c: 1, n: 6 },
      { r: 5, c: 3, n: 2 }
    ],
    solution: [
      [3, 5, 5, 5],
      [0, 5, 2, 5],
      [4, 0, 5, 2],
      [2, 0, 3, 3],
      [0, 0, 1, 4],
      [2, 4, 5, 4],
      [4, 3, 5, 3]
    ],
    artName: "Duck Pond",
    artImage: "assets/levels/duck-pond.jpg",
    difficulty: 20,
    tag: "easy",
    artPrompt: "Cozy pixel-art duck pond scene built on the Level 7 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 8 — Tavşan Bahçesi · easy (21) · Mantığa alışma
    id: "bunny-garden",
    order: 8,
    rows: 7,
    cols: 6,
    clues: [
      { r: 1, c: 0, n: 8 },
      { r: 0, c: 4, n: 2 },
      { r: 5, c: 5, n: 10 },
      { r: 4, c: 0, n: 5 },
      { r: 3, c: 1, n: 6 },
      { r: 3, c: 3, n: 4 },
      { r: 6, c: 2, n: 4 },
      { r: 6, c: 5, n: 3 }
    ],
    solution: [
      [6, 3, 6, 5],
      [0, 0, 1, 3],
      [0, 4, 0, 5],
      [2, 0, 6, 0],
      [1, 4, 5, 5],
      [5, 1, 6, 2],
      [2, 1, 4, 2],
      [2, 3, 5, 3]
    ],
    artName: "Bunny Garden",
    artImage: "assets/levels/bunny-garden-6x7.jpg",
    difficulty: 21,
    tag: "easy",
    artPrompt: "Cozy pixel-art bunny garden scene built on the Level 8 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 9 — Çay Terası · easy (21) · Mantığa alışma
    id: "tea-terrace",
    order: 9,
    rows: 6,
    cols: 5,
    clues: [
      { r: 0, c: 0, n: 8 },
      { r: 2, c: 4, n: 5 },
      { r: 3, c: 0, n: 6 },
      { r: 3, c: 3, n: 3 },
      { r: 5, c: 2, n: 6 },
      { r: 5, c: 3, n: 2 }
    ],
    solution: [
      [0, 0, 1, 3],
      [0, 4, 4, 4],
      [5, 3, 5, 4],
      [2, 3, 4, 3],
      [2, 0, 3, 2],
      [4, 0, 5, 2]
    ],
    artName: "Tea Terrace",
    artImage: "assets/levels/tea-terrace-5x6.jpg",
    difficulty: 21,
    tag: "easy",
    artPrompt: "Cozy pixel-art tea terrace scene built on the Level 9 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 10 — Kiraz Çiçeği Tapınağı · easy (21) · Dik mi yatay mı
    id: "cherry-blossom-shrine",
    order: 10,
    rows: 6,
    cols: 6,
    clues: [
      { r: 0, c: 0, n: 3 },
      { r: 1, c: 3, n: 9 },
      { r: 1, c: 0, n: 6 },
      { r: 3, c: 2, n: 6 },
      { r: 5, c: 4, n: 6 },
      { r: 4, c: 5, n: 3 },
      { r: 5, c: 1, n: 3 }
    ],
    solution: [
      [0, 0, 0, 2],
      [0, 3, 2, 5],
      [3, 5, 5, 5],
      [5, 0, 5, 2],
      [3, 3, 5, 4],
      [3, 0, 4, 2],
      [1, 0, 2, 2]
    ],
    artName: "Cherry Blossom Shrine",
    artImage: "assets/levels/cherry-blossom-shrine.jpg",
    difficulty: 21,
    tag: "easy",
    artPrompt: "Cozy pixel-art cherry blossom shrine garden scene built on the Level 10 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 11 — Fırın Avlusu · easy (22) · Mantığa alışma
    id: "bakery-courtyard",
    order: 11,
    rows: 6,
    cols: 6,
    clues: [
      { r: 0, c: 3, n: 8 },
      { r: 1, c: 4, n: 5 },
      { r: 0, c: 5, n: 5 },
      { r: 3, c: 2, n: 6 },
      { r: 2, c: 3, n: 2 },
      { r: 4, c: 0, n: 4 },
      { r: 5, c: 2, n: 6 }
    ],
    solution: [
      [0, 5, 4, 5],
      [0, 0, 1, 3],
      [0, 4, 4, 4],
      [5, 0, 5, 5],
      [2, 0, 3, 2],
      [2, 3, 3, 3],
      [4, 0, 4, 3]
    ],
    artName: "Bakery Courtyard",
    artImage: "assets/levels/bakery-courtyard.jpg",
    difficulty: 22,
    tag: "easy",
    artPrompt: "Cozy pixel-art bakery courtyard scene built on the Level 11 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 12 — Şeker Diyarı · easy (23) · Nefes molası
    id: "candy-land",
    order: 12,
    rows: 6,
    cols: 6,
    clues: [
      { r: 1, c: 0, n: 3 },
      { r: 2, c: 2, n: 6 },
      { r: 3, c: 4, n: 8 },
      { r: 2, c: 5, n: 3 },
      { r: 3, c: 0, n: 9, h: 1 },
      { r: 5, c: 5, n: 3 },
      { r: 5, c: 4, n: 4 }
    ],
    solution: [
      [3, 5, 5, 5],
      [0, 0, 2, 0],
      [0, 5, 2, 5],
      [0, 3, 3, 4],
      [4, 3, 5, 4],
      [0, 1, 2, 2],
      [3, 0, 5, 2]
    ],
    artName: "Candy Land",
    artImage: "assets/levels/candy-land.jpg",
    difficulty: 23,
    tag: "easy",
    artPrompt: "Cozy pixel-art candy land scene built on the Level 12 Shikaku region blueprint (7 zones, one continuous scene)."
  },
  {
    // Level 13 — Limon Korusu · easy (23) · Mantığa alışma
    id: "lemon-grove",
    order: 13,
    rows: 7,
    cols: 6,
    clues: [
      { r: 0, c: 0, n: 4 },
      { r: 0, c: 5, n: 8 },
      { r: 4, c: 0, n: 3 },
      { r: 4, c: 1, n: 9 },
      { r: 4, c: 4, n: 3 },
      { r: 3, c: 5, n: 3 },
      { r: 5, c: 1, n: 6 },
      { r: 6, c: 3, n: 4 },
      { r: 6, c: 4, n: 2 }
    ],
    solution: [
      [0, 2, 1, 5],
      [2, 1, 4, 3],
      [0, 0, 1, 1],
      [6, 4, 6, 5],
      [2, 5, 4, 5],
      [2, 4, 4, 4],
      [5, 0, 5, 5],
      [2, 0, 4, 0],
      [6, 0, 6, 3]
    ],
    artName: "Lemon Grove",
    artImage: "assets/levels/lemon-grove-6x7.jpg",
    difficulty: 23,
    tag: "easy",
    artPrompt: "Cozy pixel-art lemon grove scene built on the Level 13 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 14 — Kelebek Çayırı · easy (25) · Mantığa alışma
    id: "butterfly-meadow",
    order: 14,
    rows: 6,
    cols: 5,
    clues: [
      { r: 0, c: 0, n: 4 },
      { r: 0, c: 3, n: 6 },
      { r: 0, c: 4, n: 3 },
      { r: 3, c: 2, n: 9 },
      { r: 3, c: 4, n: 2 },
      { r: 5, c: 0, n: 2 },
      { r: 5, c: 3, n: 4 }
    ],
    solution: [
      [0, 4, 2, 4],
      [5, 1, 5, 4],
      [4, 0, 5, 0],
      [3, 4, 4, 4],
      [2, 1, 4, 3],
      [0, 1, 1, 3],
      [0, 0, 3, 0]
    ],
    artName: "Butterfly Meadow",
    artImage: "assets/levels/butterfly-meadow-5x6.jpg",
    difficulty: 25,
    tag: "easy",
    artPrompt: "Cozy pixel-art butterfly meadow scene built on the Level 14 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 15 — Bal Çiftliği · easy (25) · Mantığa alışma
    id: "honey-farm",
    order: 15,
    rows: 6,
    cols: 6,
    clues: [
      { r: 0, c: 0, n: 8 },
      { r: 0, c: 4, n: 2 },
      { r: 1, c: 5, n: 3 },
      { r: 4, c: 0, n: 6 },
      { r: 2, c: 2, n: 4 },
      { r: 2, c: 3, n: 8 },
      { r: 4, c: 5, n: 3 },
      { r: 5, c: 0, n: 2 }
    ],
    solution: [
      [5, 0, 5, 1],
      [2, 3, 5, 4],
      [3, 5, 5, 5],
      [0, 5, 2, 5],
      [0, 0, 1, 3],
      [0, 4, 1, 4],
      [2, 0, 4, 1],
      [2, 2, 5, 2]
    ],
    artName: "Honey Farm",
    artImage: "assets/levels/honey-farm.jpg",
    difficulty: 25,
    tag: "easy",
    artPrompt: "Cozy pixel-art honey farm scene built on the Level 15 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 16 — Sıcak Kamp Alanı · easy (26) · Mantığa alışma
    id: "cozy-campsite",
    order: 16,
    rows: 7,
    cols: 6,
    clues: [
      { r: 0, c: 1, n: 12 },
      { r: 4, c: 3, n: 12 },
      { r: 5, c: 5, n: 6 },
      { r: 4, c: 0, n: 6 },
      { r: 5, c: 2, n: 2 },
      { r: 6, c: 3, n: 2 },
      { r: 6, c: 5, n: 2 }
    ],
    solution: [
      [6, 4, 6, 5],
      [4, 0, 6, 1],
      [0, 0, 3, 2],
      [0, 5, 5, 5],
      [0, 3, 5, 4],
      [6, 2, 6, 3],
      [4, 2, 5, 2]
    ],
    artName: "Cozy Campsite",
    artImage: "assets/levels/cozy-campsite-6x7.jpg",
    difficulty: 26,
    tag: "easy",
    artPrompt: "Cozy pixel-art cozy campsite scene built on the Level 16 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 17 — Mercan Resifi · easy (28) · Çift açılış
    id: "coral-reef",
    order: 17,
    rows: 6,
    cols: 6,
    clues: [
      { r: 0, c: 3, n: 12 },
      { r: 2, c: 0, n: 8 },
      { r: 2, c: 5, n: 6 },
      { r: 4, c: 1, n: 2 },
      { r: 5, c: 2, n: 2 },
      { r: 5, c: 3, n: 2 },
      { r: 5, c: 1, n: 2 },
      { r: 5, c: 5, n: 2 }
    ],
    solution: [
      [5, 0, 5, 1],
      [4, 2, 5, 2],
      [4, 3, 5, 3],
      [5, 4, 5, 5],
      [4, 0, 4, 1],
      [2, 4, 4, 5],
      [0, 0, 1, 5],
      [2, 0, 3, 3]
    ],
    artName: "Coral Reef",
    artImage: "assets/levels/coral-reef.jpg",
    difficulty: 28,
    tag: "easy",
    artPrompt: "Cozy pixel-art underwater coral reef scene built on the Level 17 Shikaku region blueprint (7 zones, one continuous scene)."
  },
  {
    // Level 18 — Yün Atölyesi · easy (28) · Mantığa alışma
    id: "wool-workshop",
    order: 18,
    rows: 6,
    cols: 5,
    clues: [
      { r: 0, c: 0, n: 4 },
      { r: 1, c: 4, n: 4 },
      { r: 1, c: 0, n: 4 },
      { r: 4, c: 2, n: 8 },
      { r: 1, c: 3, n: 3 },
      { r: 4, c: 3, n: 4 },
      { r: 5, c: 0, n: 3 }
    ],
    solution: [
      [0, 0, 0, 3],
      [0, 4, 3, 4],
      [4, 3, 5, 4],
      [1, 3, 3, 3],
      [1, 1, 4, 2],
      [1, 0, 4, 0],
      [5, 0, 5, 2]
    ],
    artName: "Wool Workshop",
    artImage: "assets/levels/wool-workshop-5x6.jpg",
    difficulty: 28,
    tag: "easy",
    artPrompt: "Cozy pixel-art wool workshop scene built on the Level 18 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 19 — Yonca Ahırı · easy (28) · Mantığa alışma
    id: "clover-stable",
    order: 19,
    rows: 6,
    cols: 6,
    clues: [
      { r: 0, c: 0, n: 2 },
      { r: 3, c: 3, n: 12 },
      { r: 2, c: 5, n: 3 },
      { r: 1, c: 0, n: 5 },
      { r: 2, c: 1, n: 2 },
      { r: 4, c: 1, n: 3 },
      { r: 3, c: 5, n: 3 },
      { r: 5, c: 2, n: 4 },
      { r: 5, c: 4, n: 2 }
    ],
    solution: [
      [0, 0, 0, 1],
      [3, 5, 5, 5],
      [1, 0, 5, 0],
      [0, 5, 2, 5],
      [3, 1, 5, 1],
      [1, 1, 2, 1],
      [0, 2, 3, 4],
      [4, 2, 5, 3],
      [4, 4, 5, 4]
    ],
    artName: "Clover Stable",
    artImage: "assets/levels/clover-stable.jpg",
    difficulty: 28,
    tag: "easy",
    artPrompt: "Cozy pixel-art clover stable scene built on the Level 19 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 20 — Meyveli Piknik · easy (29) · Mantığa alışma
    id: "berry-picnic",
    order: 20,
    rows: 7,
    cols: 6,
    clues: [
      { r: 2, c: 0, n: 4 },
      { r: 0, c: 2, n: 4 },
      { r: 3, c: 5, n: 7 },
      { r: 2, c: 1, n: 4 },
      { r: 2, c: 3, n: 8 },
      { r: 3, c: 1, n: 4 },
      { r: 5, c: 0, n: 3 },
      { r: 5, c: 2, n: 6 },
      { r: 6, c: 4, n: 2 }
    ],
    solution: [
      [0, 5, 6, 5],
      [1, 1, 2, 2],
      [4, 0, 6, 0],
      [0, 0, 3, 0],
      [0, 1, 0, 4],
      [1, 3, 4, 4],
      [5, 4, 6, 4],
      [3, 1, 4, 2],
      [5, 1, 6, 3]
    ],
    artName: "Berry Picnic",
    artImage: "assets/levels/berry-picnic-6x7.jpg",
    difficulty: 29,
    tag: "easy",
    artPrompt: "Cozy pixel-art berry picnic scene built on the Level 20 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 21 — Yağmurlu Kitap Sokağı · medium (32) · Çok seçenekli kararlar
    id: "rainy-bookstreet",
    order: 21,
    rows: 7,
    cols: 7,
    clues: [
      { r: 1, c: 2, n: 8 },
      { r: 1, c: 5, n: 4 },
      { r: 3, c: 6, n: 4, h: 1 },
      { r: 2, c: 4, n: 6 },
      { r: 3, c: 2, n: 12 },
      { r: 4, c: 4, n: 3 },
      { r: 6, c: 5, n: 4 },
      { r: 4, c: 6, n: 3 },
      { r: 6, c: 0, n: 2 },
      { r: 6, c: 4, n: 3 }
    ],
    solution: [
      [4, 6, 6, 6],
      [6, 2, 6, 4],
      [3, 5, 6, 5],
      [6, 0, 6, 1],
      [3, 4, 5, 4],
      [0, 0, 1, 3],
      [0, 4, 1, 5],
      [3, 0, 5, 3],
      [2, 0, 2, 5],
      [0, 6, 3, 6]
    ],
    artName: "Rainy Bookstreet",
    artImage: "assets/levels/rainy-bookstreet.jpg",
    difficulty: 32,
    tag: "medium",
    artPrompt: "Cozy pixel-art rainy bookstreet scene built on the Level 21 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 22 — Liman Feneri · medium (33) · Çok seçenekli kararlar
    id: "harbor-lighthouse",
    order: 22,
    rows: 8,
    cols: 7,
    clues: [
      { r: 0, c: 0, n: 10 },
      { r: 0, c: 6, n: 4 },
      { r: 2, c: 0, n: 4 },
      { r: 2, c: 4, n: 6 },
      { r: 3, c: 6, n: 6, h: 1 },
      { r: 5, c: 1, n: 12 },
      { r: 7, c: 4, n: 8 },
      { r: 5, c: 6, n: 6 }
    ],
    solution: [
      [0, 0, 1, 4],
      [0, 5, 1, 6],
      [5, 5, 7, 6],
      [4, 3, 7, 4],
      [4, 0, 7, 2],
      [2, 0, 3, 1],
      [2, 2, 3, 4],
      [2, 5, 4, 6]
    ],
    artName: "Harbor Lighthouse",
    artImage: "assets/levels/harbor-lighthouse-7x8.jpg",
    difficulty: 33,
    tag: "medium",
    artPrompt: "Cozy pixel-art harbor lighthouse scene built on the Level 22 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 23 — Bambu Kaplıcası · medium (34) · Çok seçenekli kararlar
    id: "bamboo-onsen",
    order: 23,
    rows: 8,
    cols: 6,
    clues: [
      { r: 1, c: 2, n: 6 },
      { r: 3, c: 3, n: 8 },
      { r: 1, c: 4, n: 5 },
      { r: 0, c: 5, n: 5, h: 1 },
      { r: 2, c: 1, n: 3 },
      { r: 7, c: 0, n: 10 },
      { r: 6, c: 2, n: 5 },
      { r: 5, c: 5, n: 4 },
      { r: 7, c: 5, n: 2 }
    ],
    solution: [
      [3, 0, 7, 1],
      [7, 4, 7, 5],
      [3, 2, 7, 2],
      [2, 0, 2, 2],
      [0, 0, 1, 2],
      [0, 3, 7, 3],
      [5, 4, 6, 5],
      [0, 4, 4, 4],
      [0, 5, 4, 5]
    ],
    artName: "Bamboo Onsen",
    artImage: "assets/levels/bamboo-onsen-6x8.jpg",
    difficulty: 34,
    tag: "medium",
    artPrompt: "Cozy pixel-art bamboo onsen scene built on the Level 23 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 24 — Gül Serası · medium (35) · Çok seçenekli kararlar
    id: "rose-conservatory",
    order: 24,
    rows: 7,
    cols: 7,
    clues: [
      { r: 0, c: 0, n: 9 },
      { r: 1, c: 4, n: 12 },
      { r: 4, c: 6, n: 10, h: 1 },
      { r: 4, c: 1, n: 6 },
      { r: 5, c: 0, n: 2 },
      { r: 6, c: 2, n: 4 },
      { r: 5, c: 6, n: 4 },
      { r: 6, c: 4, n: 2 }
    ],
    solution: [
      [0, 0, 2, 2],
      [5, 5, 6, 6],
      [3, 0, 4, 2],
      [5, 1, 6, 2],
      [5, 0, 6, 0],
      [6, 3, 6, 4],
      [0, 3, 5, 4],
      [0, 5, 4, 6]
    ],
    artName: "Rose Conservatory",
    artImage: "assets/levels/rose-conservatory.jpg",
    difficulty: 35,
    tag: "medium",
    artPrompt: "Cozy pixel-art rose conservatory scene built on the Level 24 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 25 — Hasat Çiftliği · medium (36) · Dik mi yatay mı
    id: "harvest-farm",
    order: 25,
    rows: 7,
    cols: 7,
    clues: [
      { r: 1, c: 0, n: 6 },
      { r: 0, c: 3, n: 12, h: 1 },
      { r: 1, c: 5, n: 10 },
      { r: 2, c: 6, n: 3 },
      { r: 6, c: 0, n: 8 },
      { r: 3, c: 6, n: 4 },
      { r: 5, c: 4, n: 2 },
      { r: 5, c: 5, n: 2 },
      { r: 6, c: 3, n: 2 }
    ],
    solution: [
      [3, 0, 6, 1],
      [0, 6, 2, 6],
      [6, 2, 6, 3],
      [5, 4, 6, 4],
      [5, 5, 6, 5],
      [3, 6, 6, 6],
      [0, 4, 4, 5],
      [0, 2, 5, 3],
      [0, 0, 2, 1]
    ],
    artName: "Harvest Farm",
    artImage: "assets/levels/harvest-farm.jpg",
    difficulty: 36,
    tag: "medium",
    artPrompt: "Cozy pixel-art autumn harvest farm scene built on the Level 25 Shikaku region blueprint (8 zones, one continuous scene)."
  },
  {
    // Level 26 — Kitapçı Kafe · medium (36) · Nefes molası
    id: "bookshop-cafe",
    order: 26,
    rows: 7,
    cols: 7,
    clues: [
      { r: 1, c: 0, n: 8, h: 1 },
      { r: 0, c: 6, n: 9 },
      { r: 2, c: 1, n: 6 },
      { r: 2, c: 3, n: 2 },
      { r: 4, c: 4, n: 4 },
      { r: 4, c: 6, n: 6 },
      { r: 4, c: 0, n: 3 },
      { r: 4, c: 2, n: 3 },
      { r: 6, c: 1, n: 6 },
      { r: 6, c: 5, n: 2 }
    ],
    solution: [
      [0, 4, 2, 6],
      [3, 5, 5, 6],
      [6, 5, 6, 6],
      [5, 1, 6, 3],
      [4, 1, 4, 3],
      [3, 4, 6, 4],
      [2, 3, 3, 3],
      [4, 0, 6, 0],
      [0, 0, 1, 3],
      [2, 0, 3, 2]
    ],
    artName: "Bookshop Café",
    artImage: "assets/levels/bookshop-cafe.jpg",
    difficulty: 36,
    tag: "medium",
    artPrompt: "Cozy pixel-art bookshop café interior scene built on the Level 26 Shikaku region blueprint (8 zones, one continuous scene)."
  },
  {
    // Level 27 — Kanal Evleri · medium (36) · Çok seçenekli kararlar
    id: "canal-houseboats",
    order: 27,
    rows: 8,
    cols: 7,
    clues: [
      { r: 3, c: 0, n: 12 },
      { r: 2, c: 3, n: 12 },
      { r: 2, c: 6, n: 4 },
      { r: 5, c: 3, n: 6 },
      { r: 4, c: 4, n: 5 },
      { r: 5, c: 5, n: 5 },
      { r: 5, c: 6, n: 4 },
      { r: 6, c: 0, n: 4, h: 1 },
      { r: 7, c: 0, n: 4 }
    ],
    solution: [
      [7, 0, 7, 3],
      [4, 6, 7, 6],
      [3, 5, 7, 5],
      [0, 6, 3, 6],
      [3, 4, 7, 4],
      [0, 2, 2, 5],
      [0, 0, 5, 1],
      [3, 2, 5, 3],
      [6, 0, 6, 3]
    ],
    artName: "Canal Houseboats",
    artImage: "assets/levels/canal-houseboats-7x8.jpg",
    difficulty: 36,
    tag: "medium",
    artPrompt: "Cozy pixel-art canal houseboats scene built on the Level 27 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 28 — Dağ Treni · medium (37) · Çok seçenekli kararlar
    id: "mountain-railway",
    order: 28,
    rows: 8,
    cols: 6,
    clues: [
      { r: 3, c: 0, n: 6 },
      { r: 1, c: 1, n: 10, h: 1 },
      { r: 0, c: 4, n: 6 },
      { r: 3, c: 3, n: 9 },
      { r: 7, c: 1, n: 6 },
      { r: 5, c: 4, n: 4 },
      { r: 5, c: 5, n: 2 },
      { r: 7, c: 0, n: 2 },
      { r: 7, c: 3, n: 3 }
    ],
    solution: [
      [6, 0, 7, 0],
      [5, 5, 6, 5],
      [7, 3, 7, 5],
      [5, 1, 7, 2],
      [0, 0, 5, 0],
      [5, 3, 6, 4],
      [2, 3, 4, 5],
      [0, 3, 1, 5],
      [0, 1, 4, 2]
    ],
    artName: "Mountain Railway",
    artImage: "assets/levels/mountain-railway-6x8.jpg",
    difficulty: 37,
    tag: "medium",
    artPrompt: "Cozy pixel-art mountain railway scene built on the Level 28 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 29 — Eski Saatçi · medium (38) · Çok seçenekli kararlar
    id: "old-clock-shop",
    order: 29,
    rows: 7,
    cols: 7,
    clues: [
      { r: 0, c: 0, n: 9 },
      { r: 1, c: 3, n: 6 },
      { r: 2, c: 5, n: 10 },
      { r: 5, c: 0, n: 6 },
      { r: 3, c: 2, n: 4, h: 1 },
      { r: 3, c: 4, n: 2 },
      { r: 4, c: 4, n: 6 },
      { r: 6, c: 5, n: 4 },
      { r: 6, c: 1, n: 2 }
    ],
    solution: [
      [0, 0, 2, 2],
      [0, 5, 4, 6],
      [6, 0, 6, 1],
      [0, 3, 2, 4],
      [3, 3, 3, 4],
      [5, 5, 6, 6],
      [4, 3, 6, 4],
      [3, 2, 6, 2],
      [3, 0, 5, 1]
    ],
    artName: "Old Clock Shop",
    artImage: "assets/levels/old-clock-shop.jpg",
    difficulty: 38,
    tag: "medium",
    artPrompt: "Cozy pixel-art old clock shop scene built on the Level 29 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 30 — Nilüfer Köşkü · medium (39) · Çok seçenekli kararlar
    id: "lotus-pavilion",
    order: 30,
    rows: 8,
    cols: 7,
    clues: [
      { r: 1, c: 0, n: 6 },
      { r: 3, c: 1, n: 10, h: 1 },
      { r: 0, c: 3, n: 4 },
      { r: 1, c: 5, n: 4 },
      { r: 5, c: 6, n: 8 },
      { r: 5, c: 3, n: 10 },
      { r: 4, c: 5, n: 3 },
      { r: 7, c: 1, n: 6 },
      { r: 7, c: 0, n: 2 },
      { r: 7, c: 4, n: 3 }
    ],
    solution: [
      [6, 0, 7, 0],
      [0, 6, 7, 6],
      [7, 3, 7, 5],
      [5, 1, 7, 2],
      [2, 3, 6, 4],
      [4, 5, 6, 5],
      [0, 5, 3, 5],
      [0, 3, 1, 4],
      [0, 0, 5, 0],
      [0, 1, 4, 2]
    ],
    artName: "Lotus Pavilion",
    artImage: "assets/levels/lotus-pavilion-7x8.jpg",
    difficulty: 39,
    tag: "medium",
    artPrompt: "Cozy pixel-art lotus pavilion scene built on the Level 30 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 31 — Karlı Fırın · medium (40) · Çok seçenekli kararlar
    id: "snowy-bakery",
    order: 31,
    rows: 8,
    cols: 6,
    clues: [
      { r: 4, c: 0, n: 5 },
      { r: 0, c: 2, n: 8 },
      { r: 7, c: 3, n: 8, h: 1 },
      { r: 2, c: 5, n: 12 },
      { r: 6, c: 1, n: 3 },
      { r: 5, c: 2, n: 3 },
      { r: 5, c: 0, n: 2 },
      { r: 7, c: 4, n: 4 },
      { r: 7, c: 0, n: 3 }
    ],
    solution: [
      [7, 0, 7, 2],
      [6, 4, 7, 5],
      [0, 0, 4, 0],
      [4, 1, 6, 1],
      [5, 0, 6, 0],
      [4, 2, 6, 2],
      [0, 1, 3, 2],
      [0, 4, 5, 5],
      [0, 3, 7, 3]
    ],
    artName: "Snowy Bakery",
    artImage: "assets/levels/snowy-bakery-6x8.jpg",
    difficulty: 40,
    tag: "medium",
    artPrompt: "Cozy pixel-art snowy bakery scene built on the Level 31 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 32 — Çöl Vahası · medium (42) · Gizli sayı
    id: "desert-oasis",
    order: 32,
    rows: 7,
    cols: 7,
    clues: [
      { r: 0, c: 0, n: 9 },
      { r: 0, c: 6, n: 4 },
      { r: 3, c: 4, n: 12 },
      { r: 3, c: 6, n: 4 },
      { r: 3, c: 1, n: 6 },
      { r: 6, c: 0, n: 8, h: 1 },
      { r: 5, c: 4, n: 2 },
      { r: 6, c: 6, n: 2 },
      { r: 6, c: 4, n: 2 }
    ],
    solution: [
      [0, 0, 2, 2],
      [5, 4, 5, 5],
      [1, 3, 4, 5],
      [0, 3, 0, 6],
      [1, 6, 4, 6],
      [5, 6, 6, 6],
      [6, 4, 6, 5],
      [5, 0, 6, 3],
      [3, 0, 4, 2]
    ],
    artName: "Desert Oasis",
    artImage: "assets/levels/desert-oasis.jpg",
    difficulty: 42,
    tag: "medium",
    artPrompt: "Cozy pixel-art desert oasis town scene built on the Level 32 Shikaku region blueprint (7 zones, one continuous scene)."
  },
  {
    // Level 33 — Yamaç Bağı · medium (42) · Çok seçenekli kararlar
    id: "hillside-vineyard",
    order: 33,
    rows: 7,
    cols: 7,
    clues: [
      { r: 2, c: 3, n: 12 },
      { r: 0, c: 4, n: 8, h: 1 },
      { r: 0, c: 6, n: 3 },
      { r: 3, c: 2, n: 4 },
      { r: 3, c: 6, n: 4 },
      { r: 4, c: 3, n: 8 },
      { r: 5, c: 4, n: 3 },
      { r: 4, c: 5, n: 3 },
      { r: 6, c: 3, n: 4 }
    ],
    solution: [
      [0, 6, 2, 6],
      [4, 0, 5, 3],
      [6, 0, 6, 3],
      [3, 6, 6, 6],
      [4, 4, 6, 4],
      [4, 5, 6, 5],
      [3, 0, 3, 3],
      [0, 4, 3, 5],
      [0, 0, 2, 3]
    ],
    artName: "Hillside Vineyard",
    artImage: "assets/levels/hillside-vineyard.jpg",
    difficulty: 42,
    tag: "medium",
    artPrompt: "Cozy pixel-art hillside vineyard scene built on the Level 33 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 34 — Kedi Çatıları · medium (42) · Çok seçenekli kararlar
    id: "cat-rooftops",
    order: 34,
    rows: 8,
    cols: 7,
    clues: [
      { r: 1, c: 0, n: 4 },
      { r: 1, c: 2, n: 12, h: 1 },
      { r: 0, c: 6, n: 9 },
      { r: 3, c: 0, n: 6 },
      { r: 3, c: 4, n: 8 },
      { r: 3, c: 6, n: 5 },
      { r: 6, c: 1, n: 4 },
      { r: 7, c: 3, n: 4 },
      { r: 7, c: 1, n: 2 },
      { r: 7, c: 5, n: 2 }
    ],
    solution: [
      [0, 4, 2, 6],
      [3, 6, 7, 6],
      [0, 0, 1, 1],
      [3, 4, 6, 5],
      [7, 4, 7, 5],
      [2, 0, 4, 1],
      [7, 0, 7, 1],
      [5, 0, 6, 1],
      [6, 2, 7, 3],
      [0, 2, 5, 3]
    ],
    artName: "Cat Rooftops",
    artImage: "assets/levels/cat-rooftops-7x8.jpg",
    difficulty: 42,
    tag: "medium",
    artPrompt: "Cozy pixel-art cat rooftops scene built on the Level 34 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 35 — Fenerli Sokak · medium (44) · Çok seçenekli kararlar
    id: "paper-lantern-lane",
    order: 35,
    rows: 8,
    cols: 6,
    clues: [
      { r: 1, c: 1, n: 10 },
      { r: 2, c: 2, n: 8 },
      { r: 0, c: 3, n: 2 },
      { r: 4, c: 5, n: 5 },
      { r: 1, c: 4, n: 10, h: 1 },
      { r: 6, c: 0, n: 4 },
      { r: 7, c: 5, n: 3 },
      { r: 6, c: 4, n: 2 },
      { r: 7, c: 1, n: 2 },
      { r: 7, c: 4, n: 2 }
    ],
    solution: [
      [5, 5, 7, 5],
      [7, 3, 7, 4],
      [0, 0, 4, 1],
      [0, 5, 4, 5],
      [5, 0, 6, 1],
      [7, 0, 7, 1],
      [6, 3, 6, 4],
      [0, 2, 7, 2],
      [1, 3, 5, 4],
      [0, 3, 0, 4]
    ],
    artName: "Paper Lantern Lane",
    artImage: "assets/levels/paper-lantern-lane-6x8.jpg",
    difficulty: 44,
    tag: "medium",
    artPrompt: "Cozy pixel-art paper lantern lane scene built on the Level 35 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 36 — Akçaağaç Su Değirmeni · medium (44) · Çok seçenekli kararlar
    id: "maple-watermill",
    order: 36,
    rows: 7,
    cols: 7,
    clues: [
      { r: 1, c: 1, n: 4 },
      { r: 1, c: 3, n: 8 },
      { r: 0, c: 6, n: 4 },
      { r: 2, c: 0, n: 6, h: 1 },
      { r: 2, c: 2, n: 6 },
      { r: 2, c: 5, n: 2 },
      { r: 5, c: 6, n: 10 },
      { r: 6, c: 1, n: 4 },
      { r: 6, c: 6, n: 5 }
    ],
    solution: [
      [6, 2, 6, 6],
      [4, 2, 5, 6],
      [0, 6, 3, 6],
      [0, 2, 1, 5],
      [2, 5, 3, 5],
      [2, 2, 3, 4],
      [5, 0, 6, 1],
      [2, 0, 4, 1],
      [0, 0, 1, 1]
    ],
    artName: "Maple Watermill",
    artImage: "assets/levels/maple-watermill.jpg",
    difficulty: 44,
    tag: "medium",
    artPrompt: "Cozy pixel-art maple watermill scene built on the Level 36 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 37 — Kutup Gecesi · medium (46) · Çift açılış
    id: "arctic-night",
    order: 37,
    rows: 7,
    cols: 7,
    clues: [
      { r: 0, c: 1, n: 4 },
      { r: 3, c: 3, n: 12 },
      { r: 2, c: 5, n: 6 },
      { r: 4, c: 1, n: 6 },
      { r: 5, c: 5, n: 6 },
      { r: 6, c: 3, n: 6, h: 1 },
      { r: 5, c: 4, n: 3 },
      { r: 6, c: 0, n: 2 },
      { r: 6, c: 1, n: 2 },
      { r: 6, c: 5, n: 2 }
    ],
    solution: [
      [5, 0, 6, 0],
      [3, 5, 5, 6],
      [6, 5, 6, 6],
      [0, 5, 2, 6],
      [5, 1, 6, 1],
      [2, 0, 4, 1],
      [0, 0, 1, 1],
      [0, 2, 3, 4],
      [4, 4, 6, 4],
      [4, 2, 6, 3]
    ],
    artName: "Arctic Night",
    artImage: "assets/levels/arctic-night.jpg",
    difficulty: 46,
    tag: "medium",
    artPrompt: "Cozy pixel-art arctic night village scene built on the Level 37 Shikaku region blueprint (7 zones, one continuous scene)."
  },
  {
    // Level 38 — Ateşböceği Bataklığı · medium (46) · Çok seçenekli kararlar
    id: "firefly-marsh",
    order: 38,
    rows: 8,
    cols: 7,
    clues: [
      { r: 0, c: 0, n: 6 },
      { r: 0, c: 3, n: 9 },
      { r: 1, c: 5, n: 12 },
      { r: 3, c: 1, n: 8, h: 1 },
      { r: 4, c: 2, n: 3 },
      { r: 4, c: 3, n: 3 },
      { r: 5, c: 4, n: 5 },
      { r: 6, c: 2, n: 4 },
      { r: 7, c: 5, n: 2 },
      { r: 7, c: 6, n: 2 },
      { r: 7, c: 1, n: 2 }
    ],
    solution: [
      [6, 6, 7, 6],
      [7, 0, 7, 1],
      [6, 2, 7, 3],
      [6, 5, 7, 5],
      [3, 4, 7, 4],
      [0, 2, 2, 4],
      [3, 3, 5, 3],
      [0, 5, 5, 6],
      [3, 2, 5, 2],
      [0, 0, 2, 1],
      [3, 0, 6, 1]
    ],
    artName: "Firefly Marsh",
    artImage: "assets/levels/firefly-marsh-7x8.jpg",
    difficulty: 46,
    tag: "medium",
    artPrompt: "Cozy pixel-art firefly marsh scene built on the Level 38 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 39 — Cam Atölyesi · medium (47) · Çok seçenekli kararlar
    id: "glassblower-studio",
    order: 39,
    rows: 8,
    cols: 6,
    clues: [
      { r: 1, c: 0, n: 4 },
      { r: 1, c: 1, n: 4 },
      { r: 1, c: 3, n: 6 },
      { r: 0, c: 5, n: 8 },
      { r: 3, c: 2, n: 4 },
      { r: 3, c: 4, n: 6 },
      { r: 4, c: 2, n: 8, h: 1 },
      { r: 6, c: 0, n: 2 },
      { r: 7, c: 3, n: 6 }
    ],
    solution: [
      [0, 5, 7, 5],
      [0, 0, 3, 0],
      [6, 0, 7, 0],
      [6, 1, 7, 3],
      [2, 4, 7, 4],
      [0, 2, 1, 4],
      [0, 1, 3, 1],
      [2, 2, 3, 3],
      [4, 0, 5, 3]
    ],
    artName: "Glassblower Studio",
    artImage: "assets/levels/glassblower-studio-6x8.jpg",
    difficulty: 47,
    tag: "medium",
    artPrompt: "Cozy pixel-art glassblower studio scene built on the Level 39 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 40 — Deniz Kabuğu Pazarı · medium (48) · Çok seçenekli kararlar
    id: "seashell-market",
    order: 40,
    rows: 7,
    cols: 7,
    clues: [
      { r: 0, c: 2, n: 8, h: 1 },
      { r: 3, c: 4, n: 6 },
      { r: 2, c: 5, n: 4 },
      { r: 3, c: 6, n: 4 },
      { r: 4, c: 0, n: 3 },
      { r: 4, c: 1, n: 5 },
      { r: 2, c: 3, n: 4 },
      { r: 4, c: 3, n: 6 },
      { r: 5, c: 5, n: 4 },
      { r: 5, c: 0, n: 2 },
      { r: 6, c: 4, n: 3 }
    ],
    solution: [
      [2, 0, 4, 0],
      [0, 4, 5, 4],
      [5, 0, 6, 0],
      [2, 1, 6, 1],
      [0, 5, 3, 5],
      [4, 5, 5, 6],
      [0, 6, 3, 6],
      [6, 4, 6, 6],
      [4, 2, 6, 3],
      [2, 2, 3, 3],
      [0, 0, 1, 3]
    ],
    artName: "Seashell Market",
    artImage: "assets/levels/seashell-market.jpg",
    difficulty: 48,
    tag: "medium",
    artPrompt: "Cozy pixel-art seashell market scene built on the Level 40 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 41 — Yosunlu Harabeler · medium (49) · Çok seçenekli kararlar
    id: "mossy-ruins",
    order: 41,
    rows: 8,
    cols: 7,
    clues: [
      { r: 0, c: 4, n: 12 },
      { r: 3, c: 6, n: 8 },
      { r: 2, c: 1, n: 6 },
      { r: 4, c: 3, n: 4 },
      { r: 2, c: 4, n: 6, h: 1 },
      { r: 5, c: 5, n: 4 },
      { r: 6, c: 0, n: 9 },
      { r: 7, c: 3, n: 2 },
      { r: 6, c: 5, n: 2 },
      { r: 7, c: 1, n: 3 }
    ],
    solution: [
      [4, 0, 6, 2],
      [7, 0, 7, 2],
      [6, 5, 7, 5],
      [0, 6, 7, 6],
      [0, 0, 1, 5],
      [2, 0, 3, 2],
      [2, 5, 5, 5],
      [2, 3, 5, 3],
      [6, 3, 7, 3],
      [2, 4, 7, 4]
    ],
    artName: "Mossy Ruins",
    artImage: "assets/levels/mossy-ruins-7x8.jpg",
    difficulty: 49,
    tag: "medium",
    artPrompt: "Cozy pixel-art mossy ruins scene built on the Level 41 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 42 — Nehir Kıyısı Çömlekçisi · medium (50) · Çok seçenekli kararlar
    id: "riverside-pottery",
    order: 42,
    rows: 8,
    cols: 6,
    clues: [
      { r: 1, c: 1, n: 6 },
      { r: 0, c: 3, n: 6, h: 1 },
      { r: 7, c: 4, n: 8 },
      { r: 3, c: 5, n: 6 },
      { r: 4, c: 1, n: 6 },
      { r: 6, c: 2, n: 5 },
      { r: 4, c: 3, n: 3 },
      { r: 6, c: 0, n: 4 },
      { r: 7, c: 3, n: 2 },
      { r: 7, c: 5, n: 2 }
    ],
    solution: [
      [6, 5, 7, 5],
      [0, 4, 7, 4],
      [0, 5, 5, 5],
      [0, 0, 2, 1],
      [6, 0, 7, 1],
      [3, 0, 5, 1],
      [3, 3, 5, 3],
      [6, 3, 7, 3],
      [3, 2, 7, 2],
      [0, 2, 2, 3]
    ],
    artName: "Riverside Pottery",
    artImage: "assets/levels/riverside-pottery-6x8.jpg",
    difficulty: 50,
    tag: "medium",
    artPrompt: "Cozy pixel-art riverside pottery scene built on the Level 42 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 43 — Sonbahar Köprüsü · medium (51) · Çok seçenekli kararlar
    id: "autumn-bridge",
    order: 43,
    rows: 7,
    cols: 7,
    clues: [
      { r: 3, c: 0, n: 7 },
      { r: 0, c: 2, n: 4 },
      { r: 2, c: 5, n: 6 },
      { r: 2, c: 1, n: 6 },
      { r: 2, c: 3, n: 6 },
      { r: 4, c: 2, n: 4 },
      { r: 3, c: 4, n: 9, h: 1 },
      { r: 5, c: 2, n: 4 },
      { r: 6, c: 5, n: 3 }
    ],
    solution: [
      [0, 0, 6, 0],
      [6, 4, 6, 6],
      [0, 5, 2, 6],
      [1, 1, 6, 1],
      [5, 2, 6, 3],
      [0, 1, 0, 4],
      [3, 4, 5, 6],
      [3, 2, 4, 3],
      [1, 2, 2, 4]
    ],
    artName: "Autumn Bridge",
    artImage: "assets/levels/autumn-bridge.jpg",
    difficulty: 51,
    tag: "medium",
    artPrompt: "Cozy pixel-art autumn bridge scene built on the Level 43 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 44 — Tepe Gözlemevi · medium (52) · Çok seçenekli kararlar
    id: "hilltop-observatory",
    order: 44,
    rows: 8,
    cols: 7,
    clues: [
      { r: 0, c: 0, n: 6 },
      { r: 4, c: 2, n: 6 },
      { r: 3, c: 5, n: 12 },
      { r: 6, c: 6, n: 8 },
      { r: 4, c: 0, n: 6 },
      { r: 4, c: 4, n: 9, h: 1 },
      { r: 7, c: 0, n: 2 },
      { r: 7, c: 1, n: 2 },
      { r: 7, c: 2, n: 2 },
      { r: 7, c: 5, n: 3 }
    ],
    solution: [
      [6, 0, 7, 0],
      [6, 1, 7, 1],
      [3, 0, 5, 1],
      [0, 0, 2, 1],
      [0, 2, 5, 2],
      [6, 2, 7, 2],
      [7, 3, 7, 5],
      [0, 6, 7, 6],
      [0, 3, 3, 5],
      [4, 3, 6, 5]
    ],
    artName: "Hilltop Observatory",
    artImage: "assets/levels/hilltop-observatory-7x8.jpg",
    difficulty: 52,
    tag: "medium",
    artPrompt: "Cozy pixel-art hilltop observatory scene built on the Level 44 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 45 — Tropik Sera · medium (53) · Çok seçenekli kararlar
    id: "tropical-greenhouse",
    order: 45,
    rows: 8,
    cols: 6,
    clues: [
      { r: 1, c: 0, n: 4 },
      { r: 0, c: 1, n: 6 },
      { r: 5, c: 5, n: 12, h: 1 },
      { r: 5, c: 2, n: 10 },
      { r: 3, c: 3, n: 4 },
      { r: 6, c: 0, n: 3 },
      { r: 6, c: 3, n: 2 },
      { r: 6, c: 5, n: 2 },
      { r: 7, c: 0, n: 3 },
      { r: 7, c: 3, n: 2 }
    ],
    solution: [
      [7, 0, 7, 2],
      [7, 3, 7, 4],
      [6, 5, 7, 5],
      [6, 3, 6, 4],
      [4, 0, 6, 0],
      [2, 1, 6, 2],
      [0, 0, 3, 0],
      [0, 1, 1, 3],
      [0, 4, 5, 5],
      [2, 3, 5, 3]
    ],
    artName: "Tropical Greenhouse",
    artImage: "assets/levels/tropical-greenhouse-6x8.jpg",
    difficulty: 53,
    tag: "medium",
    artPrompt: "Cozy pixel-art tropical greenhouse scene built on the Level 45 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 46 — Çöl Kervanı · medium (54) · Çok seçenekli kararlar
    id: "desert-caravan",
    order: 46,
    rows: 7,
    cols: 7,
    clues: [
      { r: 0, c: 3, n: 10, h: 1 },
      { r: 0, c: 5, n: 6 },
      { r: 2, c: 1, n: 4 },
      { r: 3, c: 4, n: 4 },
      { r: 3, c: 0, n: 4 },
      { r: 3, c: 5, n: 6 },
      { r: 6, c: 0, n: 6 },
      { r: 4, c: 3, n: 2 },
      { r: 5, c: 2, n: 4 },
      { r: 6, c: 4, n: 3 }
    ],
    solution: [
      [4, 0, 6, 1],
      [6, 4, 6, 6],
      [3, 5, 5, 6],
      [0, 5, 2, 6],
      [5, 2, 6, 3],
      [4, 2, 4, 3],
      [2, 4, 5, 4],
      [3, 0, 3, 3],
      [0, 0, 1, 4],
      [2, 0, 2, 3]
    ],
    artName: "Desert Caravan",
    artImage: "assets/levels/desert-caravan.jpg",
    difficulty: 54,
    tag: "medium",
    artPrompt: "Cozy pixel-art desert caravan scene built on the Level 46 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 47 — Penguen Koyu · medium (55) · Çok seçenekli kararlar
    id: "penguin-cove",
    order: 47,
    rows: 8,
    cols: 7,
    clues: [
      { r: 0, c: 3, n: 10 },
      { r: 1, c: 5, n: 8 },
      { r: 2, c: 6, n: 3 },
      { r: 2, c: 1, n: 10 },
      { r: 5, c: 6, n: 3 },
      { r: 4, c: 0, n: 4, h: 1 },
      { r: 6, c: 2, n: 12 },
      { r: 6, c: 0, n: 2 },
      { r: 6, c: 6, n: 2 },
      { r: 7, c: 0, n: 2 }
    ],
    solution: [
      [7, 0, 7, 1],
      [6, 6, 7, 6],
      [0, 6, 2, 6],
      [6, 0, 6, 1],
      [3, 6, 5, 6],
      [0, 5, 7, 5],
      [4, 2, 7, 4],
      [0, 0, 1, 4],
      [2, 0, 3, 4],
      [4, 0, 5, 1]
    ],
    artName: "Penguin Cove",
    artImage: "assets/levels/penguin-cove-7x8.jpg",
    difficulty: 55,
    tag: "medium",
    artPrompt: "Cozy pixel-art penguin cove scene built on the Level 47 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 48 — Lunapark Gecesi · medium (56) · Nefes molası
    id: "carnival-night",
    order: 48,
    rows: 8,
    cols: 8,
    clues: [
      { r: 0, c: 0, n: 9 },
      { r: 0, c: 5, n: 9, h: 1 },
      { r: 4, c: 6, n: 10 },
      { r: 3, c: 4, n: 6 },
      { r: 6, c: 1, n: 8 },
      { r: 4, c: 3, n: 6 },
      { r: 5, c: 4, n: 3 },
      { r: 4, c: 5, n: 2 },
      { r: 6, c: 6, n: 6, h: 1 },
      { r: 6, c: 5, n: 2 },
      { r: 7, c: 3, n: 3 }
    ],
    solution: [
      [0, 0, 2, 2],
      [4, 0, 7, 1],
      [7, 2, 7, 4],
      [6, 5, 7, 5],
      [4, 4, 6, 4],
      [4, 5, 5, 5],
      [4, 2, 6, 3],
      [3, 0, 3, 5],
      [0, 6, 4, 7],
      [5, 6, 7, 7],
      [0, 3, 2, 5]
    ],
    artName: "Carnival Night",
    artImage: "assets/levels/carnival-night.jpg",
    difficulty: 56,
    tag: "medium",
    artPrompt: "Cozy pixel-art night carnival scene built on the Level 48 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 49 — Sekoya Kulübesi · medium (57) · Çok seçenekli kararlar
    id: "redwood-cabin",
    order: 49,
    rows: 8,
    cols: 6,
    clues: [
      { r: 0, c: 5, n: 6 },
      { r: 1, c: 2, n: 3 },
      { r: 1, c: 3, n: 6, h: 1 },
      { r: 2, c: 0, n: 4 },
      { r: 2, c: 1, n: 4 },
      { r: 5, c: 2, n: 6 },
      { r: 3, c: 3, n: 2 },
      { r: 7, c: 5, n: 5 },
      { r: 5, c: 4, n: 6 },
      { r: 6, c: 1, n: 4 },
      { r: 7, c: 3, n: 2 }
    ],
    solution: [
      [3, 5, 7, 5],
      [6, 0, 7, 1],
      [2, 0, 5, 0],
      [0, 0, 0, 5],
      [1, 0, 1, 2],
      [1, 3, 2, 5],
      [4, 3, 6, 4],
      [7, 3, 7, 4],
      [3, 3, 3, 4],
      [2, 2, 7, 2],
      [2, 1, 5, 1]
    ],
    artName: "Redwood Cabin",
    artImage: "assets/levels/redwood-cabin-6x8.jpg",
    difficulty: 57,
    tag: "medium",
    artPrompt: "Cozy pixel-art redwood cabin scene built on the Level 49 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 50 — Buharlı Gök Şehri · medium (57) · Dik mi yatay mı
    id: "steampunk-sky-city",
    order: 50,
    rows: 8,
    cols: 8,
    clues: [
      { r: 3, c: 0, n: 4 },
      { r: 1, c: 2, n: 8 },
      { r: 2, c: 5, n: 10 },
      { r: 6, c: 7, n: 8 },
      { r: 2, c: 2, n: 4 },
      { r: 3, c: 2, n: 2 },
      { r: 7, c: 4, n: 10, h: 1 },
      { r: 4, c: 1, n: 3, h: 1 },
      { r: 7, c: 0, n: 9 },
      { r: 5, c: 6, n: 4 },
      { r: 7, c: 6, n: 2 }
    ],
    solution: [
      [5, 0, 7, 2],
      [0, 7, 7, 7],
      [0, 5, 4, 6],
      [7, 5, 7, 6],
      [5, 5, 6, 6],
      [2, 1, 2, 4],
      [0, 1, 1, 4],
      [0, 0, 3, 0],
      [3, 3, 7, 4],
      [3, 1, 3, 2],
      [4, 0, 4, 2]
    ],
    artName: "Steampunk Sky City",
    artImage: "assets/levels/steampunk-sky-city.jpg",
    difficulty: 57,
    tag: "medium",
    artPrompt: "Cozy pixel-art steampunk sky city scene built on the Level 50 Shikaku region blueprint (11 zones, one continuous scene)."
  },
  {
    // Level 51 — Yüzen Çay Evi · hard (60) · Uzun şeritler · eleme
    id: "floating-teahouse",
    order: 51,
    rows: 9,
    cols: 8,
    clues: [
      { r: 1, c: 0, n: 8 },
      { r: 0, c: 2, n: 6, lock: 5 },
      { r: 0, c: 6, n: 10 },
      { r: 3, c: 4, n: 6 },
      { r: 4, c: 6, n: 8 },
      { r: 5, c: 0, n: 6 },
      { r: 5, c: 3, n: 5 },
      { r: 6, c: 4, n: 10, h: 1 },
      { r: 7, c: 2, n: 3 },
      { r: 7, c: 6, n: 6 },
      { r: 7, c: 0, n: 4 }
    ],
    solution: [
      [0, 3, 1, 7],
      [7, 0, 8, 1],
      [6, 2, 8, 2],
      [4, 0, 6, 1],
      [0, 0, 3, 1],
      [2, 6, 5, 7],
      [0, 2, 5, 2],
      [4, 3, 8, 3],
      [2, 3, 3, 5],
      [6, 6, 8, 7],
      [4, 4, 8, 5]
    ],
    artName: "Floating Teahouse",
    artImage: "assets/levels/floating-teahouse-8x9.jpg",
    difficulty: 60,
    tag: "hard",
    artPrompt: "Cozy pixel-art floating teahouse scene built on the Level 51 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 52 — Mercan Kütüphanesi · hard (61) · Uzun şeritler · eleme
    id: "coral-library",
    order: 52,
    rows: 8,
    cols: 8,
    clues: [
      { r: 0, c: 1, n: 4 },
      { r: 2, c: 5, n: 10 },
      { r: 2, c: 6, n: 12 },
      { r: 2, c: 0, n: 6 },
      { r: 4, c: 1, n: 5 },
      { r: 3, c: 2, n: 5 },
      { r: 2, c: 3, n: 5 },
      { r: 5, c: 4, n: 2 },
      { r: 6, c: 2, n: 7, h: 1 },
      { r: 7, c: 1, n: 6, lock: 4 },
      { r: 7, c: 6, n: 2 }
    ],
    solution: [
      [0, 4, 4, 5],
      [0, 6, 5, 7],
      [7, 6, 7, 7],
      [5, 4, 5, 5],
      [1, 2, 5, 2],
      [0, 0, 0, 3],
      [1, 3, 5, 3],
      [1, 0, 6, 0],
      [1, 1, 5, 1],
      [7, 0, 7, 5],
      [6, 1, 6, 7]
    ],
    artName: "Coral Library",
    artImage: "assets/levels/coral-library.jpg",
    difficulty: 61,
    tag: "hard",
    artPrompt: "Cozy pixel-art coral library scene built on the Level 52 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 53 — Jeot Atölyesi · hard (61) · Uzun şeritler · eleme
    id: "geode-workshop",
    order: 53,
    rows: 10,
    cols: 7,
    clues: [
      { r: 2, c: 0, n: 8 },
      { r: 0, c: 6, n: 5 },
      { r: 4, c: 3, n: 10 },
      { r: 2, c: 4, n: 6 },
      { r: 2, c: 6, n: 5 },
      { r: 5, c: 0, n: 4, lock: 3 },
      { r: 8, c: 5, n: 12, h: 1 },
      { r: 6, c: 1, n: 12 },
      { r: 9, c: 6, n: 4 },
      { r: 9, c: 1, n: 4 }
    ],
    solution: [
      [0, 2, 0, 6],
      [1, 6, 5, 6],
      [0, 0, 3, 1],
      [1, 2, 5, 3],
      [4, 0, 5, 1],
      [6, 6, 9, 6],
      [6, 0, 8, 3],
      [9, 0, 9, 3],
      [1, 4, 3, 5],
      [4, 4, 9, 5]
    ],
    artName: "Geode Workshop",
    artImage: "assets/levels/geode-workshop-7x10.jpg",
    difficulty: 61,
    tag: "hard",
    artPrompt: "Cozy pixel-art geode workshop scene built on the Level 53 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 54 — Korsan Koyu · hard (62) · Gizli sayı
    id: "pirate-cove",
    order: 54,
    rows: 8,
    cols: 8,
    clues: [
      { r: 0, c: 1, n: 6 },
      { r: 0, c: 4, n: 3 },
      { r: 2, c: 5, n: 8 },
      { r: 5, c: 6, n: 6 },
      { r: 0, c: 7, n: 5 },
      { r: 5, c: 2, n: 6 },
      { r: 6, c: 4, n: 12 },
      { r: 4, c: 1, n: 4 },
      { r: 5, c: 1, n: 6, h: 1 },
      { r: 5, c: 7, n: 3 },
      { r: 6, c: 6, n: 2, h: 1 },
      { r: 7, c: 2, n: 3 }
    ],
    solution: [
      [0, 7, 4, 7],
      [5, 7, 7, 7],
      [0, 0, 2, 1],
      [3, 0, 4, 1],
      [0, 2, 0, 4],
      [0, 6, 5, 6],
      [0, 5, 7, 5],
      [1, 3, 6, 4],
      [1, 2, 6, 2],
      [6, 6, 7, 6],
      [7, 2, 7, 4],
      [5, 0, 7, 1]
    ],
    artName: "Pirate Cove",
    artImage: "assets/levels/pirate-cove.jpg",
    difficulty: 62,
    tag: "hard",
    artPrompt: "Cozy pixel-art tropical pirate cove scene built on the Level 54 Shikaku region blueprint (9 zones, one continuous scene)."
  },
  {
    // Level 55 — Alp Saat Kulesi · hard (62) · Uzun şeritler · eleme
    id: "alpine-clocktower",
    order: 55,
    rows: 8,
    cols: 8,
    clues: [
      { r: 1, c: 1, n: 8 },
      { r: 1, c: 5, n: 8 },
      { r: 3, c: 0, n: 6, lock: 6 },
      { r: 2, c: 4, n: 6 },
      { r: 7, c: 7, n: 6 },
      { r: 5, c: 1, n: 8, h: 1 },
      { r: 4, c: 4, n: 6 },
      { r: 4, c: 5, n: 5 },
      { r: 6, c: 6, n: 5 },
      { r: 6, c: 4, n: 4 },
      { r: 7, c: 2, n: 2 }
    ],
    solution: [
      [2, 7, 7, 7],
      [3, 6, 7, 6],
      [0, 4, 1, 7],
      [0, 0, 1, 3],
      [2, 1, 2, 6],
      [3, 5, 7, 5],
      [6, 3, 7, 4],
      [3, 3, 5, 4],
      [7, 1, 7, 2],
      [2, 0, 7, 0],
      [3, 1, 6, 2]
    ],
    artName: "Alpine Clocktower",
    artImage: "assets/levels/alpine-clocktower.jpg",
    difficulty: 62,
    tag: "hard",
    artPrompt: "Cozy pixel-art alpine clocktower scene built on the Level 55 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 56 — Sualtı İstasyonu · hard (62) · Uzun şeritler · eleme
    id: "underwater-station",
    order: 56,
    rows: 9,
    cols: 8,
    clues: [
      { r: 1, c: 0, n: 16 },
      { r: 1, c: 2, n: 8 },
      { r: 3, c: 3, n: 10 },
      { r: 0, c: 6, n: 6 },
      { r: 5, c: 5, n: 12, h: 1 },
      { r: 6, c: 3, n: 4, lock: 4 },
      { r: 7, c: 4, n: 3 },
      { r: 7, c: 6, n: 6 },
      { r: 8, c: 1, n: 3 },
      { r: 8, c: 5, n: 4 }
    ],
    solution: [
      [0, 0, 7, 1],
      [8, 0, 8, 2],
      [8, 4, 8, 7],
      [5, 4, 7, 4],
      [0, 2, 7, 2],
      [0, 3, 4, 4],
      [5, 3, 8, 3],
      [6, 5, 7, 7],
      [0, 5, 1, 7],
      [2, 5, 5, 7]
    ],
    artName: "Underwater Station",
    artImage: "assets/levels/underwater-station-8x9.jpg",
    difficulty: 62,
    tag: "hard",
    artPrompt: "Cozy pixel-art underwater station scene built on the Level 56 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 57 — Ejderha Yuvası · hard (64) · Uzun şeritler · eleme
    id: "dragon-nursery",
    order: 57,
    rows: 10,
    cols: 7,
    clues: [
      { r: 8, c: 0, n: 10 },
      { r: 2, c: 1, n: 12 },
      { r: 2, c: 4, n: 10 },
      { r: 3, c: 5, n: 7 },
      { r: 2, c: 6, n: 4, h: 1 },
      { r: 8, c: 6, n: 6 },
      { r: 6, c: 3, n: 5, lock: 6 },
      { r: 8, c: 4, n: 5 },
      { r: 7, c: 1, n: 6 },
      { r: 9, c: 5, n: 3 },
      { r: 9, c: 2, n: 2 }
    ],
    solution: [
      [0, 0, 9, 0],
      [0, 3, 4, 4],
      [0, 1, 5, 2],
      [9, 1, 9, 2],
      [0, 5, 6, 5],
      [7, 5, 9, 5],
      [5, 4, 9, 4],
      [4, 6, 9, 6],
      [0, 6, 3, 6],
      [5, 3, 9, 3],
      [6, 1, 8, 2]
    ],
    artName: "Dragon Nursery",
    artImage: "assets/levels/dragon-nursery-7x10.jpg",
    difficulty: 64,
    tag: "hard",
    artPrompt: "Cozy pixel-art dragon nursery scene built on the Level 57 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 58 — Meteor Krateri · hard (65) · Uzun şeritler · eleme
    id: "meteor-crater",
    order: 58,
    rows: 8,
    cols: 8,
    clues: [
      { r: 2, c: 1, n: 12 },
      { r: 0, c: 4, n: 6, lock: 2 },
      { r: 1, c: 6, n: 8 },
      { r: 3, c: 3, n: 8 },
      { r: 3, c: 5, n: 4 },
      { r: 5, c: 1, n: 9, h: 1 },
      { r: 4, c: 6, n: 4 },
      { r: 7, c: 3, n: 6 },
      { r: 6, c: 6, n: 4 },
      { r: 7, c: 1, n: 3 }
    ],
    solution: [
      [7, 0, 7, 2],
      [6, 6, 7, 7],
      [6, 3, 7, 5],
      [4, 6, 5, 7],
      [2, 5, 5, 5],
      [0, 6, 3, 7],
      [2, 3, 5, 4],
      [0, 0, 3, 2],
      [0, 3, 1, 5],
      [4, 0, 6, 2]
    ],
    artName: "Meteor Crater",
    artImage: "assets/levels/meteor-crater.jpg",
    difficulty: 65,
    tag: "hard",
    artPrompt: "Cozy pixel-art meteor crater scene built on the Level 58 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 59 — Büyülü Tezgâh · hard (66) · Uzun şeritler · eleme
    id: "enchanted-loom",
    order: 59,
    rows: 9,
    cols: 8,
    clues: [
      { r: 3, c: 0, n: 6, h: 1 },
      { r: 0, c: 2, n: 6 },
      { r: 7, c: 7, n: 9 },
      { r: 2, c: 2, n: 8 },
      { r: 1, c: 4, n: 6 },
      { r: 6, c: 6, n: 8 },
      { r: 4, c: 4, n: 6 },
      { r: 5, c: 3, n: 8, lock: 5 },
      { r: 6, c: 5, n: 2 },
      { r: 7, c: 0, n: 3 },
      { r: 8, c: 3, n: 10 }
    ],
    solution: [
      [0, 7, 8, 7],
      [7, 1, 8, 5],
      [6, 0, 8, 0],
      [1, 6, 8, 6],
      [0, 1, 0, 6],
      [1, 1, 4, 2],
      [1, 3, 2, 5],
      [3, 3, 4, 5],
      [5, 1, 6, 4],
      [5, 5, 6, 5],
      [0, 0, 5, 0]
    ],
    artName: "Enchanted Loom",
    artImage: "assets/levels/enchanted-loom-8x9.jpg",
    difficulty: 66,
    tag: "hard",
    artPrompt: "Cozy pixel-art enchanted loom scene built on the Level 59 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 60 — Dinozor Vadisi · hard (66) · Çift açılış
    id: "dinosaur-valley",
    order: 60,
    rows: 8,
    cols: 8,
    clues: [
      { r: 1, c: 0, n: 3 },
      { r: 1, c: 3, n: 10 },
      { r: 1, c: 7, n: 4 },
      { r: 2, c: 6, n: 6 },
      { r: 2, c: 7, n: 3 },
      { r: 3, c: 1, n: 8 },
      { r: 4, c: 5, n: 6 },
      { r: 5, c: 2, n: 8, h: 1 },
      { r: 7, c: 0, n: 2 },
      { r: 7, c: 1, n: 4 },
      { r: 6, c: 4, n: 6 },
      { r: 7, c: 7, n: 4 }
    ],
    solution: [
      [6, 0, 7, 0],
      [2, 7, 4, 7],
      [0, 6, 1, 7],
      [0, 0, 2, 0],
      [3, 0, 4, 3],
      [0, 1, 1, 5],
      [2, 1, 2, 6],
      [3, 4, 4, 6],
      [5, 0, 5, 7],
      [6, 6, 7, 7],
      [6, 1, 7, 2],
      [6, 3, 7, 5]
    ],
    artName: "Dinosaur Valley",
    artImage: "assets/levels/dinosaur-valley.jpg",
    difficulty: 66,
    tag: "hard",
    artPrompt: "Cozy pixel-art prehistoric dinosaur valley scene built on the Level 60 Shikaku region blueprint (9 zones, one continuous scene)."
  },
  {
    // Level 61 — Ay Işığı Akvaryumu · hard (66) · Uzun şeritler · eleme
    id: "moonlit-aquarium",
    order: 61,
    rows: 10,
    cols: 7,
    clues: [
      { r: 6, c: 0, n: 8, lock: 4 },
      { r: 1, c: 2, n: 12 },
      { r: 3, c: 4, n: 10 },
      { r: 5, c: 6, n: 5 },
      { r: 4, c: 2, n: 16, h: 1 },
      { r: 4, c: 5, n: 4 },
      { r: 8, c: 6, n: 3 },
      { r: 9, c: 3, n: 8 },
      { r: 9, c: 4, n: 2 },
      { r: 9, c: 5, n: 2 }
    ],
    solution: [
      [8, 4, 9, 4],
      [8, 5, 9, 5],
      [7, 6, 9, 6],
      [0, 1, 1, 6],
      [2, 6, 6, 6],
      [4, 5, 7, 5],
      [2, 1, 3, 5],
      [8, 0, 9, 3],
      [0, 0, 7, 0],
      [4, 1, 7, 4]
    ],
    artName: "Moonlit Aquarium",
    artImage: "assets/levels/moonlit-aquarium-7x10.jpg",
    difficulty: 66,
    tag: "hard",
    artPrompt: "Cozy pixel-art moonlit aquarium scene built on the Level 61 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 62 — Bulut Değirmenleri · hard (68) · Uzun şeritler · eleme
    id: "cloud-windmills",
    order: 62,
    rows: 8,
    cols: 8,
    clues: [
      { r: 2, c: 0, n: 5 },
      { r: 1, c: 2, n: 10 },
      { r: 2, c: 6, n: 8, lock: 4 },
      { r: 5, c: 1, n: 12, h: 1 },
      { r: 2, c: 3, n: 5 },
      { r: 3, c: 4, n: 5 },
      { r: 4, c: 5, n: 4 },
      { r: 5, c: 6, n: 4 },
      { r: 5, c: 7, n: 4 },
      { r: 5, c: 0, n: 3 },
      { r: 7, c: 5, n: 2 },
      { r: 7, c: 3, n: 2 }
    ],
    solution: [
      [0, 0, 4, 0],
      [5, 0, 7, 0],
      [4, 7, 7, 7],
      [0, 1, 1, 5],
      [2, 3, 6, 3],
      [0, 6, 3, 7],
      [2, 4, 6, 4],
      [4, 6, 7, 6],
      [2, 5, 5, 5],
      [6, 5, 7, 5],
      [7, 3, 7, 4],
      [2, 1, 7, 2]
    ],
    artName: "Cloud Windmills",
    artImage: "assets/levels/cloud-windmills.jpg",
    difficulty: 68,
    tag: "hard",
    artPrompt: "Cozy pixel-art cloud windmills scene built on the Level 62 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 63 — Buz Sarayı · hard (69) · Uzun şeritler · eleme
    id: "frost-palace",
    order: 63,
    rows: 10,
    cols: 7,
    clues: [
      { r: 0, c: 3, n: 7 },
      { r: 3, c: 0, n: 6 },
      { r: 1, c: 2, n: 9, h: 1 },
      { r: 6, c: 4, n: 8 },
      { r: 1, c: 5, n: 4 },
      { r: 5, c: 5, n: 14, lock: 2 },
      { r: 5, c: 2, n: 12 },
      { r: 5, c: 3, n: 5 },
      { r: 8, c: 0, n: 3 },
      { r: 9, c: 3, n: 2 }
    ],
    solution: [
      [0, 0, 0, 6],
      [7, 0, 9, 0],
      [4, 1, 9, 2],
      [1, 0, 6, 0],
      [1, 5, 2, 6],
      [3, 5, 9, 6],
      [1, 4, 8, 4],
      [9, 3, 9, 4],
      [4, 3, 8, 3],
      [1, 1, 3, 3]
    ],
    artName: "Frost Palace",
    artImage: "assets/levels/frost-palace-7x10.jpg",
    difficulty: 69,
    tag: "hard",
    artPrompt: "Cozy pixel-art frost palace scene built on the Level 63 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 64 — Kehribar Ormanı · hard (69) · Uzun şeritler · eleme
    id: "amber-forest",
    order: 64,
    rows: 9,
    cols: 8,
    clues: [
      { r: 0, c: 6, n: 8 },
      { r: 3, c: 1, n: 9 },
      { r: 2, c: 3, n: 6 },
      { r: 2, c: 6, n: 6 },
      { r: 5, c: 6, n: 12, lock: 5 },
      { r: 6, c: 7, n: 6 },
      { r: 4, c: 2, n: 8 },
      { r: 4, c: 4, n: 5, h: 1 },
      { r: 6, c: 1, n: 4 },
      { r: 8, c: 2, n: 8 }
    ],
    solution: [
      [1, 0, 3, 2],
      [4, 0, 5, 3],
      [0, 0, 0, 7],
      [1, 3, 3, 4],
      [7, 0, 8, 3],
      [6, 0, 6, 3],
      [1, 5, 2, 7],
      [4, 4, 8, 4],
      [3, 5, 8, 6],
      [3, 7, 8, 7]
    ],
    artName: "Amber Forest",
    artImage: "assets/levels/amber-forest-8x9.jpg",
    difficulty: 69,
    tag: "hard",
    artPrompt: "Cozy pixel-art amber forest scene built on the Level 64 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 65 — Saat Mekanizmalı Liman · hard (71) · Uzun şeritler · eleme
    id: "clockwork-harbor",
    order: 65,
    rows: 8,
    cols: 8,
    clues: [
      { r: 0, c: 1, n: 5 },
      { r: 6, c: 6, n: 16, lock: 4 },
      { r: 3, c: 7, n: 6 },
      { r: 2, c: 0, n: 10 },
      { r: 2, c: 2, n: 4 },
      { r: 4, c: 3, n: 5 },
      { r: 3, c: 4, n: 7, h: 1 },
      { r: 6, c: 2, n: 3 },
      { r: 6, c: 0, n: 4 },
      { r: 7, c: 3, n: 2 },
      { r: 7, c: 7, n: 2 }
    ],
    solution: [
      [1, 0, 5, 1],
      [6, 0, 7, 1],
      [0, 0, 0, 4],
      [0, 7, 5, 7],
      [6, 7, 7, 7],
      [0, 5, 7, 6],
      [1, 3, 5, 3],
      [1, 2, 4, 2],
      [5, 2, 7, 2],
      [6, 3, 7, 3],
      [1, 4, 7, 4]
    ],
    artName: "Clockwork Harbor",
    artImage: "assets/levels/clockwork-harbor.jpg",
    difficulty: 71,
    tag: "hard",
    artPrompt: "Cozy pixel-art clockwork harbor scene built on the Level 65 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 66 — Mantar Ormanı Peri Köyü · hard (71) · Dik mi yatay mı
    id: "mushroom-village",
    order: 66,
    rows: 9,
    cols: 8,
    clues: [
      { r: 2, c: 2, n: 16, h: 1 },
      { r: 1, c: 5, n: 10 },
      { r: 0, c: 6, n: 7 },
      { r: 1, c: 7, n: 6 },
      { r: 6, c: 0, n: 12 },
      { r: 5, c: 3, n: 4 },
      { r: 6, c: 4, n: 3, lock: 3 },
      { r: 6, c: 5, n: 3 },
      { r: 8, c: 7, n: 3 },
      { r: 8, c: 6, n: 2 },
      { r: 8, c: 2, n: 6 }
    ],
    solution: [
      [6, 7, 8, 7],
      [7, 6, 8, 6],
      [0, 7, 5, 7],
      [0, 6, 6, 6],
      [0, 4, 4, 5],
      [5, 5, 7, 5],
      [8, 0, 8, 5],
      [4, 0, 7, 2],
      [5, 4, 7, 4],
      [4, 3, 7, 3],
      [0, 0, 3, 3]
    ],
    artName: "Mushroom Village",
    artImage: "assets/levels/mushroom-village-8x9.jpg",
    difficulty: 71,
    tag: "hard",
    artPrompt: "Cozy pixel-art mushroom forest fairy village scene built on the Level 66 Shikaku region blueprint (9 zones, one continuous scene)."
  },
  {
    // Level 67 — Nilüfer Mağarası · hard (71) · Uzun şeritler · eleme
    id: "lotus-cavern",
    order: 67,
    rows: 9,
    cols: 8,
    clues: [
      { r: 2, c: 0, n: 8 },
      { r: 5, c: 2, n: 7 },
      { r: 1, c: 3, n: 8 },
      { r: 0, c: 5, n: 6, h: 1 },
      { r: 5, c: 5, n: 10 },
      { r: 3, c: 7, n: 5 },
      { r: 6, c: 0, n: 5 },
      { r: 8, c: 1, n: 5 },
      { r: 5, c: 4, n: 6 },
      { r: 7, c: 4, n: 6 },
      { r: 8, c: 3, n: 6, lock: 2 }
    ],
    solution: [
      [4, 1, 8, 1],
      [4, 0, 8, 0],
      [0, 0, 3, 1],
      [0, 2, 6, 2],
      [8, 2, 8, 7],
      [7, 2, 7, 7],
      [2, 5, 6, 6],
      [2, 7, 6, 7],
      [4, 3, 6, 4],
      [0, 3, 3, 4],
      [0, 5, 1, 7]
    ],
    artName: "Lotus Cavern",
    artImage: "assets/levels/lotus-cavern-8x9.jpg",
    difficulty: 71,
    tag: "hard",
    artPrompt: "Cozy pixel-art lotus cavern scene built on the Level 67 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 68 — Çöl Gezegeni · hard (72) · Uzun şeritler · eleme
    id: "desert-planet",
    order: 68,
    rows: 10,
    cols: 7,
    clues: [
      { r: 0, c: 4, n: 5 },
      { r: 0, c: 5, n: 10 },
      { r: 2, c: 6, n: 4 },
      { r: 4, c: 0, n: 7, h: 1 },
      { r: 3, c: 1, n: 6 },
      { r: 3, c: 2, n: 6 },
      { r: 4, c: 3, n: 7 },
      { r: 6, c: 4, n: 7 },
      { r: 8, c: 6, n: 6 },
      { r: 8, c: 1, n: 6, lock: 4 },
      { r: 8, c: 0, n: 2 },
      { r: 9, c: 4, n: 4 }
    ],
    solution: [
      [0, 5, 9, 5],
      [8, 0, 9, 0],
      [4, 6, 9, 6],
      [0, 6, 3, 6],
      [0, 0, 0, 4],
      [1, 4, 7, 4],
      [1, 3, 7, 3],
      [1, 2, 6, 2],
      [8, 3, 9, 4],
      [7, 1, 9, 2],
      [1, 1, 6, 1],
      [1, 0, 7, 0]
    ],
    artName: "Desert Planet",
    artImage: "assets/levels/desert-planet-7x10.jpg",
    difficulty: 72,
    tag: "hard",
    artPrompt: "Cozy pixel-art desert planet scene built on the Level 68 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 69 — Ağaç Evler Köyü · hard (73) · Uzun şeritler · eleme
    id: "treehouse-village",
    order: 69,
    rows: 8,
    cols: 8,
    clues: [
      { r: 0, c: 0, n: 5 },
      { r: 2, c: 1, n: 4 },
      { r: 0, c: 4, n: 6 },
      { r: 1, c: 5, n: 5 },
      { r: 4, c: 7, n: 5 },
      { r: 3, c: 5, n: 10, h: 1 },
      { r: 5, c: 2, n: 12 },
      { r: 6, c: 4, n: 4 },
      { r: 5, c: 6, n: 8 },
      { r: 6, c: 0, n: 3 },
      { r: 7, c: 7, n: 2, lock: 4 }
    ],
    solution: [
      [0, 0, 4, 0],
      [5, 0, 7, 0],
      [4, 5, 7, 6],
      [4, 1, 7, 3],
      [4, 4, 7, 4],
      [0, 1, 3, 1],
      [0, 2, 0, 7],
      [1, 2, 1, 6],
      [1, 7, 5, 7],
      [6, 7, 7, 7],
      [2, 2, 3, 6]
    ],
    artName: "Treehouse Village",
    artImage: "assets/levels/treehouse-village.jpg",
    difficulty: 73,
    tag: "hard",
    artPrompt: "Cozy pixel-art treehouse village scene built on the Level 69 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 70 — Gece Sakura Treni · hard (74) · Uzun şeritler · eleme
    id: "sakura-night-train",
    order: 70,
    rows: 9,
    cols: 8,
    clues: [
      { r: 6, c: 0, n: 16, lock: 3 },
      { r: 0, c: 3, n: 5 },
      { r: 1, c: 7, n: 9 },
      { r: 1, c: 3, n: 12 },
      { r: 2, c: 6, n: 5, h: 1 },
      { r: 5, c: 2, n: 10 },
      { r: 7, c: 4, n: 5 },
      { r: 4, c: 5, n: 3 },
      { r: 7, c: 6, n: 3 },
      { r: 8, c: 5, n: 2 },
      { r: 8, c: 1, n: 2 }
    ],
    solution: [
      [0, 7, 8, 7],
      [4, 2, 8, 3],
      [7, 5, 8, 5],
      [6, 6, 8, 6],
      [4, 4, 8, 4],
      [4, 5, 6, 5],
      [8, 0, 8, 1],
      [1, 2, 3, 5],
      [0, 0, 7, 1],
      [0, 2, 0, 6],
      [1, 6, 5, 6]
    ],
    artName: "Sakura Night Train",
    artImage: "assets/levels/sakura-night-train-8x9.jpg",
    difficulty: 74,
    tag: "hard",
    artPrompt: "Cozy pixel-art sakura night train scene built on the Level 70 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 71 — Volkan Kaplıcası · hard (75) · Uzun şeritler · eleme
    id: "volcanic-spa",
    order: 71,
    rows: 10,
    cols: 7,
    clues: [
      { r: 0, c: 2, n: 7 },
      { r: 2, c: 0, n: 4 },
      { r: 8, c: 1, n: 9 },
      { r: 3, c: 2, n: 9, h: 1 },
      { r: 2, c: 3, n: 6 },
      { r: 6, c: 5, n: 7, lock: 3 },
      { r: 5, c: 6, n: 9 },
      { r: 7, c: 3, n: 5 },
      { r: 7, c: 4, n: 5 },
      { r: 6, c: 0, n: 5 },
      { r: 8, c: 5, n: 2 },
      { r: 9, c: 3, n: 2 }
    ],
    solution: [
      [0, 0, 0, 6],
      [1, 6, 9, 6],
      [8, 5, 9, 5],
      [4, 4, 8, 4],
      [9, 3, 9, 4],
      [4, 3, 8, 3],
      [1, 1, 9, 1],
      [1, 0, 4, 0],
      [5, 0, 9, 0],
      [1, 3, 3, 4],
      [1, 5, 7, 5],
      [1, 2, 9, 2]
    ],
    artName: "Volcanic Spa",
    artImage: "assets/levels/volcanic-spa-7x10.jpg",
    difficulty: 75,
    tag: "hard",
    artPrompt: "Cozy pixel-art volcanic spa scene built on the Level 71 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 72 — Kristal Mağarası · hard (76) · Gizli sayı
    id: "crystal-cave",
    order: 72,
    rows: 10,
    cols: 7,
    clues: [
      { r: 1, c: 1, n: 6 },
      { r: 3, c: 2, n: 7, h: 1 },
      { r: 3, c: 3, n: 9 },
      { r: 2, c: 4, n: 5, lock: 3 },
      { r: 1, c: 6, n: 6 },
      { r: 4, c: 1, n: 6 },
      { r: 6, c: 5, n: 6 },
      { r: 7, c: 6, n: 6 },
      { r: 7, c: 4, n: 4 },
      { r: 8, c: 1, n: 6 },
      { r: 7, c: 2, n: 2 },
      { r: 9, c: 5, n: 7 }
    ],
    solution: [
      [9, 0, 9, 6],
      [6, 0, 8, 1],
      [3, 6, 8, 6],
      [7, 2, 8, 2],
      [0, 3, 8, 3],
      [0, 5, 2, 6],
      [3, 5, 8, 5],
      [5, 4, 8, 4],
      [0, 4, 4, 4],
      [3, 0, 5, 1],
      [0, 0, 2, 1],
      [0, 2, 6, 2]
    ],
    artName: "Crystal Cave",
    artImage: "assets/levels/crystal-cave-7x10.jpg",
    difficulty: 76,
    tag: "hard",
    artPrompt: "Cozy pixel-art crystal cave mine scene built on the Level 72 Shikaku region blueprint (9 zones, one continuous scene)."
  },
  {
    // Level 73 — Göksel Bahçe · hard (77) · Uzun şeritler · eleme
    id: "celestial-garden",
    order: 73,
    rows: 9,
    cols: 8,
    clues: [
      { r: 2, c: 0, n: 7 },
      { r: 2, c: 1, n: 6 },
      { r: 2, c: 4, n: 12 },
      { r: 4, c: 6, n: 5 },
      { r: 1, c: 7, n: 9 },
      { r: 4, c: 2, n: 10 },
      { r: 6, c: 4, n: 5, h: 1 },
      { r: 5, c: 5, n: 5 },
      { r: 8, c: 6, n: 4 },
      { r: 7, c: 1, n: 3, lock: 4 },
      { r: 7, c: 0, n: 2 },
      { r: 8, c: 3, n: 4 }
    ],
    solution: [
      [0, 0, 6, 0],
      [7, 0, 8, 0],
      [0, 7, 8, 7],
      [0, 6, 4, 6],
      [0, 2, 2, 5],
      [0, 1, 5, 1],
      [3, 2, 7, 3],
      [5, 6, 8, 6],
      [3, 5, 7, 5],
      [8, 2, 8, 5],
      [6, 1, 8, 1],
      [3, 4, 7, 4]
    ],
    artName: "Celestial Garden",
    artImage: "assets/levels/celestial-garden-8x9.jpg",
    difficulty: 77,
    tag: "hard",
    artPrompt: "Cozy pixel-art celestial garden scene built on the Level 73 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 74 — Batık Avlu · hard (77) · Uzun şeritler · eleme
    id: "sunken-courtyard",
    order: 74,
    rows: 8,
    cols: 8,
    clues: [
      { r: 0, c: 2, n: 5 },
      { r: 1, c: 6, n: 6 },
      { r: 3, c: 1, n: 6 },
      { r: 6, c: 2, n: 7 },
      { r: 3, c: 3, n: 5 },
      { r: 1, c: 4, n: 4, lock: 6 },
      { r: 3, c: 5, n: 8 },
      { r: 3, c: 7, n: 6 },
      { r: 6, c: 0, n: 8, h: 1 },
      { r: 6, c: 4, n: 3 },
      { r: 7, c: 3, n: 2 },
      { r: 6, c: 5, n: 4 }
    ],
    solution: [
      [1, 2, 7, 2],
      [6, 5, 7, 6],
      [2, 7, 7, 7],
      [0, 5, 1, 7],
      [0, 0, 0, 4],
      [2, 5, 5, 6],
      [1, 3, 5, 3],
      [6, 3, 7, 3],
      [5, 4, 7, 4],
      [1, 4, 4, 4],
      [4, 0, 7, 1],
      [1, 0, 3, 1]
    ],
    artName: "Sunken Courtyard",
    artImage: "assets/levels/sunken-courtyard.jpg",
    difficulty: 77,
    tag: "hard",
    artPrompt: "Cozy pixel-art sunken courtyard scene built on the Level 74 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 75 — Kutup Işığı Köyü · hard (78) · Uzun şeritler · eleme
    id: "aurora-village",
    order: 75,
    rows: 10,
    cols: 7,
    clues: [
      { r: 0, c: 0, n: 3 },
      { r: 7, c: 1, n: 10 },
      { r: 0, c: 2, n: 8 },
      { r: 2, c: 6, n: 7, lock: 3 },
      { r: 3, c: 4, n: 12, h: 1 },
      { r: 6, c: 0, n: 5 },
      { r: 5, c: 3, n: 3 },
      { r: 6, c: 5, n: 5 },
      { r: 7, c: 3, n: 12 },
      { r: 8, c: 6, n: 3 },
      { r: 8, c: 0, n: 2 }
    ],
    solution: [
      [0, 0, 2, 0],
      [3, 0, 7, 0],
      [8, 0, 9, 0],
      [7, 6, 9, 6],
      [0, 1, 9, 1],
      [5, 2, 5, 4],
      [0, 2, 1, 5],
      [6, 2, 9, 4],
      [5, 5, 9, 5],
      [0, 6, 6, 6],
      [2, 2, 4, 5]
    ],
    artName: "Aurora Village",
    artImage: "assets/levels/aurora-village-7x10.jpg",
    difficulty: 78,
    tag: "hard",
    artPrompt: "Cozy pixel-art aurora village scene built on the Level 75 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 76 — Taş Devler Vadisi · hard (78) · Uzun şeritler · eleme
    id: "stone-giant-valley",
    order: 76,
    rows: 8,
    cols: 8,
    clues: [
      { r: 0, c: 1, n: 8 },
      { r: 1, c: 1, n: 6 },
      { r: 3, c: 3, n: 10, lock: 5 },
      { r: 5, c: 5, n: 5 },
      { r: 3, c: 6, n: 4 },
      { r: 4, c: 7, n: 7 },
      { r: 5, c: 1, n: 12, h: 1 },
      { r: 6, c: 6, n: 3 },
      { r: 7, c: 4, n: 6 },
      { r: 7, c: 1, n: 3 }
    ],
    solution: [
      [0, 0, 0, 7],
      [1, 7, 7, 7],
      [7, 0, 7, 2],
      [5, 6, 7, 6],
      [1, 6, 4, 6],
      [1, 5, 5, 5],
      [6, 3, 7, 5],
      [1, 3, 5, 4],
      [1, 0, 2, 2],
      [3, 0, 6, 2]
    ],
    artName: "Stone Giant Valley",
    artImage: "assets/levels/stone-giant-valley.jpg",
    difficulty: 78,
    tag: "hard",
    artPrompt: "Cozy pixel-art stone giant valley scene built on the Level 76 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 77 — Oyuncak Atölyesi · hard (80) · Çift açılış · Kesişim ve eleme
    id: "toy-workshop",
    order: 77,
    rows: 9,
    cols: 8,
    clues: [
      { r: 1, c: 0, n: 9 },
      { r: 2, c: 1, n: 5 },
      { r: 1, c: 3, n: 14 },
      { r: 1, c: 4, n: 5 },
      { r: 4, c: 5, n: 8 },
      { r: 5, c: 6, n: 8, h: 1 },
      { r: 3, c: 7, n: 7, lock: 4 },
      { r: 7, c: 1, n: 4 },
      { r: 6, c: 4, n: 3 },
      { r: 7, c: 3, n: 4 },
      { r: 7, c: 7, n: 2 },
      { r: 8, c: 5, n: 3 }
    ],
    solution: [
      [0, 0, 8, 0],
      [0, 2, 6, 3],
      [0, 4, 4, 4],
      [0, 1, 4, 1],
      [5, 1, 8, 1],
      [7, 2, 8, 3],
      [0, 5, 7, 5],
      [5, 4, 7, 4],
      [8, 4, 8, 6],
      [7, 7, 8, 7],
      [0, 7, 6, 7],
      [0, 6, 7, 6]
    ],
    artName: "Toy Workshop",
    artImage: "assets/levels/toy-workshop-8x9.jpg",
    difficulty: 80,
    tag: "hard",
    artPrompt: "Cozy pixel-art toy maker's workshop interior scene built on the Level 77 Shikaku region blueprint (12 zones, one continuous scene)."
  },
  {
    // Level 78 — Kanyon Manastırı · hard (80) · Uzun şeritler · eleme
    id: "canyon-monastery",
    order: 78,
    rows: 9,
    cols: 8,
    clues: [
      { r: 2, c: 1, n: 10, h: 1 },
      { r: 3, c: 3, n: 10 },
      { r: 1, c: 5, n: 10 },
      { r: 3, c: 6, n: 4 },
      { r: 2, c: 7, n: 6 },
      { r: 7, c: 6, n: 5 },
      { r: 6, c: 0, n: 4 },
      { r: 6, c: 4, n: 12 },
      { r: 7, c: 5, n: 3 },
      { r: 7, c: 7, n: 3, lock: 5 },
      { r: 8, c: 2, n: 3 },
      { r: 8, c: 5, n: 2 }
    ],
    solution: [
      [4, 6, 8, 6],
      [8, 4, 8, 5],
      [8, 1, 8, 3],
      [5, 0, 8, 0],
      [5, 5, 7, 5],
      [5, 1, 7, 4],
      [0, 6, 3, 6],
      [0, 7, 5, 7],
      [6, 7, 8, 7],
      [0, 4, 4, 5],
      [0, 2, 4, 3],
      [0, 0, 4, 1]
    ],
    artName: "Canyon Monastery",
    artImage: "assets/levels/canyon-monastery-8x9.jpg",
    difficulty: 80,
    tag: "hard",
    artPrompt: "Cozy pixel-art canyon monastery scene built on the Level 78 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 79 — Mekanik Bahçe · hard (81) · Uzun şeritler · eleme
    id: "mechanical-garden",
    order: 79,
    rows: 10,
    cols: 7,
    clues: [
      { r: 0, c: 2, n: 7 },
      { r: 4, c: 0, n: 5 },
      { r: 6, c: 1, n: 9 },
      { r: 1, c: 4, n: 5, lock: 6 },
      { r: 3, c: 2, n: 6 },
      { r: 2, c: 3, n: 12, h: 1 },
      { r: 8, c: 5, n: 8 },
      { r: 6, c: 6, n: 8 },
      { r: 8, c: 0, n: 4 },
      { r: 8, c: 3, n: 6 }
    ],
    solution: [
      [0, 0, 0, 6],
      [2, 6, 9, 6],
      [1, 0, 5, 0],
      [6, 0, 9, 0],
      [1, 1, 9, 1],
      [2, 5, 9, 5],
      [8, 2, 9, 4],
      [2, 2, 7, 2],
      [1, 2, 1, 6],
      [2, 3, 7, 4]
    ],
    artName: "Mechanical Garden",
    artImage: "assets/levels/mechanical-garden-7x10.jpg",
    difficulty: 81,
    tag: "hard",
    artPrompt: "Cozy pixel-art mechanical garden scene built on the Level 79 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 80 — Perili Köşk · hard (81) · Çift gizli sayı
    id: "haunted-manor",
    order: 80,
    rows: 10,
    cols: 7,
    clues: [
      { r: 1, c: 0, n: 10 },
      { r: 2, c: 1, n: 4 },
      { r: 0, c: 2, n: 4 },
      { r: 3, c: 4, n: 15, lock: 2 },
      { r: 3, c: 2, n: 8, h: 1 },
      { r: 4, c: 3, n: 5 },
      { r: 8, c: 1, n: 6 },
      { r: 6, c: 4, n: 8, h: 1 },
      { r: 6, c: 6, n: 5 },
      { r: 8, c: 3, n: 3 },
      { r: 9, c: 5, n: 2 }
    ],
    solution: [
      [0, 0, 9, 0],
      [7, 3, 9, 3],
      [9, 4, 9, 5],
      [5, 6, 9, 6],
      [2, 3, 6, 3],
      [0, 2, 1, 3],
      [0, 1, 3, 1],
      [4, 1, 9, 1],
      [2, 2, 9, 2],
      [0, 4, 4, 6],
      [5, 4, 8, 5]
    ],
    artName: "Haunted Manor",
    artImage: "assets/levels/haunted-manor-7x10.jpg",
    difficulty: 81,
    tag: "hard",
    artPrompt: "Cozy pixel-art cute-spooky Halloween manor scene built on the Level 80 Shikaku region blueprint (8 zones, one continuous scene)."
  },
  {
    // Level 81 — Fırtına Kulesi · expert (83) · Uzak hücre ilişkileri · kesişim
    id: "stormwatch-tower",
    order: 81,
    rows: 10,
    cols: 8,
    clues: [
      { r: 9, c: 0, n: 10, lock: 3 },
      { r: 1, c: 3, n: 16 },
      { r: 1, c: 5, n: 8 },
      { r: 4, c: 7, n: 8, h: 1 },
      { r: 4, c: 2, n: 6, h: 1 },
      { r: 6, c: 3, n: 9 },
      { r: 5, c: 5, n: 9 },
      { r: 8, c: 2, n: 7 },
      { r: 9, c: 1, n: 4 },
      { r: 9, c: 6, n: 3 }
    ],
    solution: [
      [9, 1, 9, 4],
      [9, 5, 9, 7],
      [8, 1, 8, 7],
      [5, 1, 7, 3],
      [5, 4, 7, 6],
      [0, 5, 3, 6],
      [0, 1, 3, 4],
      [0, 0, 9, 0],
      [0, 7, 7, 7],
      [4, 1, 4, 6]
    ],
    artName: "Stormwatch Tower",
    artImage: "assets/levels/stormwatch-tower-8x10.jpg",
    difficulty: 83,
    tag: "expert",
    artPrompt: "Cozy pixel-art stormwatch tower scene built on the Level 81 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 82 — Gelgit Tapınağı · expert (84) · Uzak hücre ilişkileri · kesişim
    id: "tidal-temple",
    order: 82,
    rows: 9,
    cols: 8,
    clues: [
      { r: 0, c: 2, n: 7, h: 1 },
      { r: 3, c: 7, n: 6 },
      { r: 2, c: 1, n: 12 },
      { r: 1, c: 2, n: 12, lock: 2 },
      { r: 2, c: 6, n: 5 },
      { r: 7, c: 2, n: 5, h: 1 },
      { r: 6, c: 4, n: 8 },
      { r: 7, c: 5, n: 5 },
      { r: 7, c: 6, n: 6 },
      { r: 7, c: 0, n: 2 },
      { r: 7, c: 1, n: 2 },
      { r: 8, c: 3, n: 2 }
    ],
    solution: [
      [7, 0, 8, 0],
      [7, 1, 8, 1],
      [4, 5, 8, 5],
      [1, 0, 6, 1],
      [8, 3, 8, 4],
      [4, 3, 7, 4],
      [1, 2, 3, 5],
      [4, 2, 8, 2],
      [1, 6, 5, 6],
      [6, 6, 8, 7],
      [0, 7, 5, 7],
      [0, 0, 0, 6]
    ],
    artName: "Tidal Temple",
    artImage: "assets/levels/tidal-temple-8x9.jpg",
    difficulty: 84,
    tag: "expert",
    artPrompt: "Cozy pixel-art tidal temple scene built on the Level 82 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 83 — Savana Gün Batımı · expert (84) · Gizli sayı
    id: "savanna-sunset",
    order: 83,
    rows: 10,
    cols: 8,
    clues: [
      { r: 0, c: 1, n: 9 },
      { r: 1, c: 3, n: 6 },
      { r: 3, c: 4, n: 5 },
      { r: 4, c: 5, n: 8 },
      { r: 7, c: 6, n: 10, lock: 2 },
      { r: 4, c: 7, n: 6 },
      { r: 4, c: 1, n: 9 },
      { r: 7, c: 4, n: 5 },
      { r: 7, c: 1, n: 9, h: 1 },
      { r: 7, c: 3, n: 3 },
      { r: 7, c: 7, n: 4 },
      { r: 8, c: 5, n: 2 },
      { r: 9, c: 2, n: 4 }
    ],
    solution: [
      [0, 0, 2, 2],
      [6, 7, 9, 7],
      [0, 7, 5, 7],
      [0, 6, 9, 6],
      [0, 5, 7, 5],
      [8, 5, 9, 5],
      [0, 3, 5, 3],
      [6, 3, 8, 3],
      [3, 0, 5, 2],
      [0, 4, 4, 4],
      [5, 4, 9, 4],
      [9, 0, 9, 3],
      [6, 0, 8, 2]
    ],
    artName: "Savanna Sunset",
    artImage: "assets/levels/savanna-sunset-8x10.jpg",
    difficulty: 84,
    tag: "expert",
    artPrompt: "Cozy pixel-art golden-hour savanna scene built on the Level 83 Shikaku region blueprint (9 zones, one continuous scene)."
  },
  {
    // Level 84 — Balina Sığınağı · expert (85) · Uzak hücre ilişkileri · kesişim
    id: "whale-sanctuary",
    order: 84,
    rows: 10,
    cols: 7,
    clues: [
      { r: 0, c: 2, n: 8 },
      { r: 2, c: 4, n: 4 },
      { r: 5, c: 5, n: 7, h: 1 },
      { r: 2, c: 6, n: 6 },
      { r: 5, c: 1, n: 14 },
      { r: 8, c: 2, n: 8 },
      { r: 4, c: 3, n: 4, h: 1 },
      { r: 5, c: 4, n: 4 },
      { r: 6, c: 3, n: 4 },
      { r: 7, c: 6, n: 4 },
      { r: 8, c: 5, n: 3 },
      { r: 8, c: 4, n: 2, lock: 6 },
      { r: 9, c: 0, n: 2 }
    ],
    solution: [
      [7, 5, 9, 5],
      [6, 6, 9, 6],
      [9, 0, 9, 1],
      [2, 2, 9, 2],
      [2, 0, 8, 1],
      [0, 0, 1, 3],
      [0, 4, 3, 4],
      [4, 4, 7, 4],
      [6, 3, 9, 3],
      [8, 4, 9, 4],
      [2, 3, 5, 3],
      [0, 6, 5, 6],
      [0, 5, 6, 5]
    ],
    artName: "Whale Sanctuary",
    artImage: "assets/levels/whale-sanctuary-7x10.jpg",
    difficulty: 85,
    tag: "expert",
    artPrompt: "Cozy pixel-art whale sanctuary scene built on the Level 84 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 85 — Kristal Gözlemevi · expert (86) · Uzak hücre ilişkileri · kesişim
    id: "crystal-observatory",
    order: 85,
    rows: 10,
    cols: 8,
    clues: [
      { r: 1, c: 3, n: 10, h: 1 },
      { r: 0, c: 6, n: 9, h: 1 },
      { r: 3, c: 1, n: 9 },
      { r: 3, c: 3, n: 8, lock: 3 },
      { r: 4, c: 5, n: 3 },
      { r: 4, c: 6, n: 3 },
      { r: 4, c: 7, n: 7 },
      { r: 6, c: 0, n: 8 },
      { r: 7, c: 2, n: 4 },
      { r: 7, c: 5, n: 16 },
      { r: 9, c: 0, n: 3 }
    ],
    solution: [
      [3, 6, 5, 6],
      [6, 3, 9, 6],
      [3, 5, 5, 5],
      [3, 7, 9, 7],
      [9, 0, 9, 2],
      [5, 2, 8, 2],
      [2, 0, 4, 2],
      [5, 0, 8, 1],
      [2, 3, 5, 4],
      [0, 5, 2, 7],
      [0, 0, 1, 4]
    ],
    artName: "Crystal Observatory",
    artImage: "assets/levels/crystal-observatory-8x10.jpg",
    difficulty: 86,
    tag: "expert",
    artPrompt: "Cozy pixel-art crystal observatory scene built on the Level 85 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 86 — Gökyüzü Arşivi · expert (88) · Uzak hücre ilişkileri · kesişim
    id: "sky-archive",
    order: 86,
    rows: 9,
    cols: 8,
    clues: [
      { r: 0, c: 4, n: 12, h: 1 },
      { r: 4, c: 6, n: 8 },
      { r: 1, c: 7, n: 6 },
      { r: 4, c: 0, n: 10 },
      { r: 3, c: 3, n: 8 },
      { r: 5, c: 3, n: 8, h: 1 },
      { r: 5, c: 4, n: 5 },
      { r: 5, c: 5, n: 4, lock: 5 },
      { r: 7, c: 7, n: 3 },
      { r: 8, c: 0, n: 4 },
      { r: 8, c: 2, n: 2 },
      { r: 8, c: 5, n: 2 }
    ],
    solution: [
      [6, 7, 8, 7],
      [8, 2, 8, 3],
      [7, 0, 8, 1],
      [2, 0, 6, 1],
      [2, 2, 3, 5],
      [4, 4, 8, 4],
      [4, 2, 7, 3],
      [0, 6, 7, 6],
      [0, 7, 5, 7],
      [8, 5, 8, 6],
      [4, 5, 7, 5],
      [0, 0, 1, 5]
    ],
    artName: "Sky Archive",
    artImage: "assets/levels/sky-archive-8x9.jpg",
    difficulty: 88,
    tag: "expert",
    artPrompt: "Cozy pixel-art sky archive scene built on the Level 86 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 87 — Ay Üssü · expert (89) · Çok seçenekli kararlar
    id: "moon-base",
    order: 87,
    rows: 10,
    cols: 8,
    clues: [
      { r: 1, c: 0, n: 4 },
      { r: 2, c: 1, n: 6 },
      { r: 0, c: 3, n: 5 },
      { r: 1, c: 7, n: 5 },
      { r: 7, c: 2, n: 9 },
      { r: 2, c: 4, n: 10, lock: 3 },
      { r: 2, c: 5, n: 4 },
      { r: 2, c: 6, n: 9 },
      { r: 8, c: 0, n: 5 },
      { r: 6, c: 5, n: 5 },
      { r: 7, c: 7, n: 5, h: 1 },
      { r: 7, c: 1, n: 3, h: 1 },
      { r: 7, c: 3, n: 8 },
      { r: 9, c: 0, n: 2 }
    ],
    solution: [
      [9, 0, 9, 1],
      [1, 2, 9, 2],
      [4, 0, 8, 0],
      [0, 0, 3, 0],
      [1, 6, 9, 6],
      [5, 5, 9, 5],
      [1, 5, 4, 5],
      [0, 2, 0, 6],
      [0, 7, 4, 7],
      [0, 1, 5, 1],
      [6, 1, 8, 1],
      [5, 7, 9, 7],
      [1, 3, 5, 4],
      [6, 3, 9, 4]
    ],
    artName: "Moon Base",
    artImage: "assets/levels/moon-base-8x10.jpg",
    difficulty: 89,
    tag: "expert",
    artPrompt: "Cozy pixel-art moon base scene built on the Level 87 Shikaku region blueprint (12 zones, one continuous scene)."
  },
  {
    // Level 88 — Antik Uzay Limanı · expert (89) · Uzak hücre ilişkileri · kesişim
    id: "ancient-starport",
    order: 88,
    rows: 10,
    cols: 7,
    clues: [
      { r: 2, c: 0, n: 5 },
      { r: 1, c: 3, n: 10, h: 1 },
      { r: 1, c: 6, n: 7, lock: 2 },
      { r: 5, c: 1, n: 5 },
      { r: 3, c: 3, n: 8 },
      { r: 4, c: 4, n: 6 },
      { r: 6, c: 0, n: 5 },
      { r: 6, c: 5, n: 10 },
      { r: 7, c: 3, n: 6, h: 1 },
      { r: 8, c: 1, n: 3 },
      { r: 8, c: 6, n: 3 },
      { r: 9, c: 3, n: 2 }
    ],
    solution: [
      [7, 6, 9, 6],
      [9, 2, 9, 3],
      [7, 1, 9, 1],
      [5, 0, 9, 0],
      [2, 1, 6, 1],
      [0, 0, 4, 0],
      [0, 6, 6, 6],
      [2, 2, 5, 3],
      [5, 4, 9, 5],
      [2, 4, 4, 5],
      [6, 2, 8, 3],
      [0, 1, 1, 5]
    ],
    artName: "Ancient Starport",
    artImage: "assets/levels/ancient-starport-7x10.jpg",
    difficulty: 89,
    tag: "expert",
    artPrompt: "Cozy pixel-art ancient starport scene built on the Level 88 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 89 — Mercan Hisarı · expert (90) · Uzak hücre ilişkileri · kesişim
    id: "coral-citadel",
    order: 89,
    rows: 10,
    cols: 8,
    clues: [
      { r: 0, c: 2, n: 5 },
      { r: 1, c: 5, n: 4 },
      { r: 1, c: 6, n: 4 },
      { r: 1, c: 7, n: 5 },
      { r: 3, c: 1, n: 10 },
      { r: 5, c: 4, n: 15, lock: 5 },
      { r: 7, c: 6, n: 12, h: 1 },
      { r: 6, c: 7, n: 5 },
      { r: 7, c: 0, n: 12 },
      { r: 7, c: 3, n: 4, h: 1 },
      { r: 6, c: 4, n: 4 }
    ],
    solution: [
      [0, 7, 4, 7],
      [5, 7, 9, 7],
      [6, 0, 9, 2],
      [6, 4, 9, 4],
      [1, 0, 5, 1],
      [0, 0, 0, 4],
      [0, 6, 3, 6],
      [0, 5, 3, 5],
      [1, 2, 5, 4],
      [6, 3, 9, 3],
      [4, 5, 9, 6]
    ],
    artName: "Coral Citadel",
    artImage: "assets/levels/coral-citadel-8x10.jpg",
    difficulty: 90,
    tag: "expert",
    artPrompt: "Cozy pixel-art coral citadel scene built on the Level 89 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 90 — Tutulma Pagodası · expert (91) · Uzak hücre ilişkileri · kesişim
    id: "eclipse-pagoda",
    order: 90,
    rows: 9,
    cols: 8,
    clues: [
      { r: 0, c: 2, n: 7 },
      { r: 6, c: 7, n: 9, h: 1 },
      { r: 1, c: 2, n: 5 },
      { r: 2, c: 5, n: 10 },
      { r: 2, c: 1, n: 4 },
      { r: 4, c: 4, n: 5 },
      { r: 5, c: 1, n: 12, lock: 5 },
      { r: 4, c: 2, n: 3 },
      { r: 7, c: 3, n: 6 },
      { r: 7, c: 2, n: 3 },
      { r: 8, c: 6, n: 6, h: 1 },
      { r: 7, c: 4, n: 2 }
    ],
    solution: [
      [0, 0, 0, 6],
      [2, 4, 6, 4],
      [7, 4, 8, 4],
      [3, 3, 8, 3],
      [6, 2, 8, 2],
      [2, 0, 2, 3],
      [3, 2, 5, 2],
      [1, 0, 1, 4],
      [1, 5, 5, 6],
      [3, 0, 8, 1],
      [6, 5, 8, 6],
      [0, 7, 8, 7]
    ],
    artName: "Eclipse Pagoda",
    artImage: "assets/levels/eclipse-pagoda-8x9.jpg",
    difficulty: 91,
    tag: "expert",
    artPrompt: "Cozy pixel-art eclipse pagoda scene built on the Level 90 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 91 — Viking Fiyortu · expert (92) · Çift açılış
    id: "viking-fjord",
    order: 91,
    rows: 10,
    cols: 8,
    clues: [
      { r: 0, c: 4, n: 6 },
      { r: 1, c: 7, n: 6 },
      { r: 6, c: 0, n: 7 },
      { r: 3, c: 1, n: 7 },
      { r: 4, c: 2, n: 7 },
      { r: 2, c: 4, n: 8 },
      { r: 5, c: 5, n: 6, h: 1 },
      { r: 6, c: 7, n: 10, lock: 5 },
      { r: 8, c: 4, n: 10 },
      { r: 8, c: 5, n: 3 },
      { r: 8, c: 1, n: 6 },
      { r: 8, c: 6, n: 4 }
    ],
    solution: [
      [7, 5, 9, 5],
      [5, 3, 9, 4],
      [1, 3, 4, 4],
      [1, 2, 7, 2],
      [8, 0, 9, 2],
      [1, 0, 7, 0],
      [1, 1, 7, 1],
      [0, 0, 0, 5],
      [0, 6, 2, 7],
      [3, 6, 7, 7],
      [8, 6, 9, 7],
      [1, 5, 6, 5]
    ],
    artName: "Viking Fjord",
    artImage: "assets/levels/viking-fjord-8x10.jpg",
    difficulty: 92,
    tag: "expert",
    artPrompt: "Cozy pixel-art Viking fjord village scene built on the Level 91 Shikaku region blueprint (10 zones, one continuous scene)."
  },
  {
    // Level 92 — Düş Dokuyucu Kulesi · expert (93) · Uzak hücre ilişkileri · kesişim
    id: "dream-weaver-tower",
    order: 92,
    rows: 10,
    cols: 7,
    clues: [
      { r: 2, c: 3, n: 15, lock: 2 },
      { r: 0, c: 5, n: 5 },
      { r: 2, c: 6, n: 4 },
      { r: 4, c: 0, n: 5 },
      { r: 5, c: 3, n: 12 },
      { r: 7, c: 4, n: 6 },
      { r: 7, c: 6, n: 5, h: 1 },
      { r: 6, c: 5, n: 4, h: 1 },
      { r: 8, c: 1, n: 9 },
      { r: 8, c: 0, n: 2 },
      { r: 9, c: 5, n: 3 }
    ],
    solution: [
      [8, 0, 9, 0],
      [3, 0, 7, 0],
      [0, 5, 4, 5],
      [0, 6, 3, 6],
      [0, 0, 2, 4],
      [7, 1, 9, 3],
      [3, 4, 8, 4],
      [3, 1, 6, 3],
      [9, 4, 9, 6],
      [4, 6, 8, 6],
      [5, 5, 8, 5]
    ],
    artName: "Dream Weaver Tower",
    artImage: "assets/levels/dream-weaver-tower-7x10.jpg",
    difficulty: 93,
    tag: "expert",
    artPrompt: "Cozy pixel-art dream weaver tower scene built on the Level 92 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 93 — Obsidyen Şelalesi · expert (94) · Uzak hücre ilişkileri · kesişim
    id: "obsidian-waterfall",
    order: 93,
    rows: 10,
    cols: 8,
    clues: [
      { r: 5, c: 0, n: 10 },
      { r: 6, c: 1, n: 8 },
      { r: 1, c: 3, n: 4 },
      { r: 1, c: 4, n: 9 },
      { r: 1, c: 7, n: 5 },
      { r: 4, c: 2, n: 12, h: 1 },
      { r: 5, c: 4, n: 5 },
      { r: 7, c: 5, n: 12 },
      { r: 6, c: 7, n: 3, lock: 2 },
      { r: 8, c: 2, n: 8, h: 1 },
      { r: 8, c: 7, n: 2 },
      { r: 9, c: 6, n: 2 }
    ],
    solution: [
      [0, 7, 4, 7],
      [0, 4, 2, 6],
      [0, 0, 9, 0],
      [3, 5, 8, 6],
      [9, 5, 9, 6],
      [8, 7, 9, 7],
      [5, 7, 7, 7],
      [3, 4, 7, 4],
      [0, 1, 7, 1],
      [8, 1, 9, 4],
      [0, 2, 1, 3],
      [2, 2, 7, 3]
    ],
    artName: "Obsidian Waterfall",
    artImage: "assets/levels/obsidian-waterfall-8x10.jpg",
    difficulty: 94,
    tag: "expert",
    artPrompt: "Cozy pixel-art obsidian waterfall scene built on the Level 93 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 94 — Ay Botanik Kubbesi · expert (94) · Uzak hücre ilişkileri · kesişim
    id: "lunar-botanical-dome",
    order: 94,
    rows: 9,
    cols: 8,
    clues: [
      { r: 2, c: 3, n: 16 },
      { r: 3, c: 5, n: 16, lock: 3 },
      { r: 5, c: 1, n: 6 },
      { r: 4, c: 4, n: 5 },
      { r: 5, c: 5, n: 5, h: 1 },
      { r: 7, c: 1, n: 6, h: 1 },
      { r: 7, c: 4, n: 6 },
      { r: 6, c: 6, n: 2 },
      { r: 7, c: 7, n: 3 },
      { r: 8, c: 0, n: 5 },
      { r: 8, c: 5, n: 2 }
    ],
    solution: [
      [6, 7, 8, 7],
      [8, 5, 8, 6],
      [6, 6, 7, 6],
      [0, 0, 3, 3],
      [6, 3, 7, 5],
      [8, 0, 8, 4],
      [0, 4, 3, 7],
      [4, 3, 4, 7],
      [4, 0, 5, 2],
      [6, 0, 7, 2],
      [5, 3, 5, 7]
    ],
    artName: "Lunar Botanical Dome",
    artImage: "assets/levels/lunar-botanical-dome-8x9.jpg",
    difficulty: 94,
    tag: "expert",
    artPrompt: "Cozy pixel-art lunar botanical dome scene built on the Level 94 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 95 — Gökyüzü Adaları · expert (96) · Gizli sayı · Kesişim ve eleme
    id: "sky-islands",
    order: 95,
    rows: 10,
    cols: 8,
    clues: [
      { r: 3, c: 1, n: 10, h: 1 },
      { r: 5, c: 2, n: 7 },
      { r: 5, c: 3, n: 10 },
      { r: 7, c: 4, n: 10, h: 1 },
      { r: 1, c: 5, n: 6 },
      { r: 1, c: 7, n: 7 },
      { r: 5, c: 5, n: 12 },
      { r: 6, c: 0, n: 5 },
      { r: 7, c: 1, n: 5 },
      { r: 8, c: 2, n: 3, lock: 6 },
      { r: 8, c: 7, n: 2 },
      { r: 9, c: 6, n: 3 }
    ],
    solution: [
      [0, 7, 6, 7],
      [5, 1, 9, 1],
      [5, 0, 9, 0],
      [0, 2, 6, 2],
      [0, 0, 4, 1],
      [0, 3, 9, 3],
      [7, 2, 9, 2],
      [7, 7, 8, 7],
      [9, 5, 9, 7],
      [3, 5, 8, 6],
      [0, 5, 2, 6],
      [0, 4, 9, 4]
    ],
    artName: "Sky Islands",
    artImage: "assets/levels/sky-islands-8x10.jpg",
    difficulty: 96,
    tag: "expert",
    artPrompt: "Cozy pixel-art floating sky islands scene built on the Level 95 Shikaku region blueprint (12 zones, one continuous scene)."
  },
  {
    // Level 96 — Zaman Bekçisi Avlusu · expert (96) · Uzak hücre ilişkileri · kesişim
    id: "timekeeper-atrium",
    order: 96,
    rows: 10,
    cols: 7,
    clues: [
      { r: 1, c: 0, n: 4 },
      { r: 2, c: 2, n: 4 },
      { r: 1, c: 4, n: 6, h: 1 },
      { r: 7, c: 5, n: 9 },
      { r: 1, c: 6, n: 5 },
      { r: 3, c: 1, n: 6, lock: 4 },
      { r: 7, c: 3, n: 12 },
      { r: 6, c: 2, n: 5 },
      { r: 6, c: 1, n: 6 },
      { r: 6, c: 6, n: 5, h: 1 },
      { r: 8, c: 1, n: 4 },
      { r: 9, c: 2, n: 4 }
    ],
    solution: [
      [0, 6, 4, 6],
      [3, 3, 8, 4],
      [5, 6, 9, 6],
      [4, 2, 8, 2],
      [0, 5, 8, 5],
      [9, 2, 9, 5],
      [8, 0, 9, 1],
      [5, 0, 7, 1],
      [0, 2, 3, 2],
      [0, 3, 2, 4],
      [2, 0, 4, 1],
      [0, 0, 1, 1]
    ],
    artName: "Timekeeper Atrium",
    artImage: "assets/levels/timekeeper-atrium-7x10.jpg",
    difficulty: 96,
    tag: "expert",
    artPrompt: "Cozy pixel-art timekeeper atrium scene built on the Level 96 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 97 — Prizma Kanyonu · expert (98) · Uzak hücre ilişkileri · kesişim
    id: "prismatic-canyon",
    order: 97,
    rows: 10,
    cols: 8,
    clues: [
      { r: 2, c: 1, n: 8, h: 1 },
      { r: 2, c: 2, n: 8 },
      { r: 0, c: 4, n: 4 },
      { r: 2, c: 5, n: 8 },
      { r: 2, c: 7, n: 8, lock: 3 },
      { r: 5, c: 1, n: 10, h: 1 },
      { r: 6, c: 5, n: 6 },
      { r: 6, c: 6, n: 6 },
      { r: 8, c: 0, n: 8 },
      { r: 7, c: 3, n: 9 },
      { r: 8, c: 7, n: 2 },
      { r: 9, c: 2, n: 3 }
    ],
    solution: [
      [8, 7, 9, 7],
      [4, 6, 9, 6],
      [6, 0, 9, 1],
      [0, 5, 3, 6],
      [0, 4, 3, 4],
      [0, 7, 7, 7],
      [9, 2, 9, 4],
      [4, 5, 9, 5],
      [6, 2, 8, 4],
      [0, 2, 3, 3],
      [4, 0, 5, 4],
      [0, 0, 3, 1]
    ],
    artName: "Prismatic Canyon",
    artImage: "assets/levels/prismatic-canyon-8x10.jpg",
    difficulty: 98,
    tag: "expert",
    artPrompt: "Cozy pixel-art prismatic canyon scene built on the Level 97 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 98 — Yıldızlı Ejderha Korusu · expert (99) · Uzak hücre ilişkileri · kesişim
    id: "starlight-dragon-grove",
    order: 98,
    rows: 9,
    cols: 8,
    clues: [
      { r: 1, c: 0, n: 5 },
      { r: 0, c: 1, n: 6 },
      { r: 2, c: 4, n: 7 },
      { r: 0, c: 6, n: 6, h: 1 },
      { r: 3, c: 2, n: 6 },
      { r: 3, c: 5, n: 6, h: 1 },
      { r: 3, c: 7, n: 4 },
      { r: 4, c: 2, n: 3 },
      { r: 5, c: 1, n: 8, lock: 5 },
      { r: 7, c: 5, n: 8 },
      { r: 7, c: 7, n: 3 },
      { r: 8, c: 1, n: 4 },
      { r: 7, c: 2, n: 3 },
      { r: 8, c: 4, n: 3 }
    ],
    solution: [
      [6, 7, 8, 7],
      [2, 7, 5, 7],
      [0, 0, 4, 0],
      [0, 4, 6, 4],
      [4, 1, 4, 3],
      [0, 1, 1, 3],
      [2, 1, 3, 3],
      [7, 2, 7, 4],
      [5, 0, 6, 3],
      [7, 0, 8, 1],
      [8, 2, 8, 4],
      [5, 5, 8, 6],
      [2, 5, 4, 6],
      [0, 5, 1, 7]
    ],
    artName: "Starlight Dragon Grove",
    artImage: "assets/levels/starlight-dragon-grove-8x9.jpg",
    difficulty: 99,
    tag: "expert",
    artPrompt: "Cozy pixel-art starlight dragon grove scene built on the Level 98 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 99 — Şafak Dünya Ağacı · expert (100) · Uzak hücre ilişkileri · kesişim
    id: "dawn-worldtree",
    order: 99,
    rows: 10,
    cols: 7,
    clues: [
      { r: 4, c: 0, n: 10, lock: 2 },
      { r: 2, c: 1, n: 5 },
      { r: 4, c: 2, n: 6 },
      { r: 3, c: 3, n: 9, h: 1 },
      { r: 2, c: 4, n: 9 },
      { r: 0, c: 6, n: 4 },
      { r: 6, c: 5, n: 7 },
      { r: 6, c: 6, n: 6 },
      { r: 6, c: 1, n: 5 },
      { r: 7, c: 2, n: 3 },
      { r: 9, c: 6, n: 2 },
      { r: 9, c: 4, n: 4, h: 1 }
    ],
    solution: [
      [0, 1, 4, 1],
      [5, 1, 9, 1],
      [0, 0, 9, 0],
      [0, 5, 1, 6],
      [2, 5, 8, 5],
      [2, 6, 7, 6],
      [8, 6, 9, 6],
      [0, 4, 8, 4],
      [0, 2, 5, 2],
      [6, 2, 8, 2],
      [9, 2, 9, 5],
      [0, 3, 8, 3]
    ],
    artName: "Dawn Worldtree",
    artImage: "assets/levels/dawn-worldtree-7x10.jpg",
    difficulty: 100,
    tag: "expert",
    artPrompt: "Cozy pixel-art dawn worldtree scene built on the Level 99 Shikaku region blueprint (6 zones, one continuous scene)."
  },
  {
    // Level 100 — Orman Tapınağı · expert (100) · Çift açılış · Gizli sayı
    id: "jungle-temple",
    order: 100,
    rows: 10,
    cols: 8,
    clues: [
      { r: 4, c: 0, n: 7 },
      { r: 4, c: 1, n: 14, h: 1 },
      { r: 1, c: 5, n: 12 },
      { r: 3, c: 6, n: 5, lock: 4 },
      { r: 1, c: 7, n: 5 },
      { r: 4, c: 4, n: 9 },
      { r: 6, c: 6, n: 6 },
      { r: 7, c: 1, n: 6 },
      { r: 8, c: 2, n: 7 },
      { r: 8, c: 7, n: 2, h: 1 },
      { r: 9, c: 3, n: 5 },
      { r: 9, c: 6, n: 2 }
    ],
    solution: [
      [0, 7, 4, 7],
      [9, 0, 9, 4],
      [9, 5, 9, 6],
      [8, 0, 8, 6],
      [0, 0, 6, 0],
      [7, 0, 7, 5],
      [5, 6, 7, 7],
      [8, 7, 9, 7],
      [4, 3, 6, 5],
      [0, 3, 3, 5],
      [0, 6, 4, 6],
      [0, 1, 6, 2]
    ],
    artName: "Jungle Temple",
    artImage: "assets/levels/jungle-temple-8x10.jpg",
    difficulty: 100,
    tag: "expert",
    artPrompt: "Cozy pixel-art ancient jungle temple ruins scene built on the Level 100 Shikaku region blueprint (13 zones, one continuous scene)."
  }
];

if (typeof module !== "undefined") module.exports = PIXHAKU_LEVELS_4_100;
