"use strict";
// Pixhaku Level 4–23 — kaynak veri. build_pack.js bunu doğrular ve
// pixhaku_level_creation_4-23.html, taslaklar/*.png ve levels_4-23.js dosyalarını üretir.
//
//   artGrid  görselin bölge düzeni (taslak PNG, bölge tablosu ve prompt bunu kullanır); her harf bir
//            dikdörtgen bölge, numaralar sol üst köşelerin okuma sırası
//   spec     bulmaca profili (tools/shikaku.js → checkSpec): cols × rows = tahta (en fazla 8 geniş, 10 yüksek), start = boş tahtadaki
//            kesin açılış sayısı, t1Max = en fazla "kendiliğinden belli" parça oranı, decMin = karar anı,
//            liveMin = karar anında ortalama seçenek, deepMin = kesişim/eleme hamlesi, effortTarget…
//   puzzle   oyundaki bulmaca: grid (parçalar), clues (parça → ipucu hücresi [satır, sütun]), hidden ("?"
//            parçalar). Görselin bölgelerinden bağımsız. Yeniden üretmek için `puzzle: null,` yazıp
//            `node tools/build_pack.js --search` çalıştır.
//   zones    görsel bölgesi → [içerik (TR), prompt satırı (EN), taslak rengi]
//   scene    görsel prompt şablonunun sahneye özel parçaları
//   id       sabit kimlik (görsel ve taslak dosya adları); oyundaki level sırası build'de zorluk
//            skoruna göre belirlenir
module.exports = [
  {
    id: "cherry-blossom-shrine", variety: "Dik mi yatay mı",
    tr: "Kiraz Çiçeği Tapınağı", artName: "Cherry Blossom Shrine",
    artGrid: [
      "AAAPP",
      "AAAPP",
      "CTTPP",
      "CTTKK",
      "CLLKK",
    ],
    spec: { cols: 6, rows: 6, start: [1, 1], maxTech: 4, pieces: [7, 10], effortTarget: 30, t1Max: 0.5, decMin: 3, liveMin: 2.3, deepMin: 0, hiddenCount: 0 },
    puzzle: {
      grid: [
        "AAABBB",
        "CCCBBB",
        "CCCBBB",
        "DDDEEF",
        "DDDEEF",
        "GGGEEF",
      ],
      clues: { A: [0, 0], B: [1, 3], C: [1, 0], D: [3, 2], E: [5, 4], F: [4, 5], G: [5, 1] },
      hidden: [],
    },
    zones: {
      A: ["Bahar sabahı göğü, uzakta karlı dağ zirvesi", "spring morning sky with a distant snow-capped mountain", "#a9d8ef"],
      P: ["Beş katlı kırmızı pagoda", "five-tiered red pagoda on a small hill", "#e0685a"],
      C: ["Çiçek açmış uzun kiraz ağacı", "tall cherry tree in full bloom", "#f2a7c3"],
      T: ["Yosunlu bahçede turuncu torii kapısı", "moss garden with a vermilion torii gate", "#8fc177"],
      K: ["Nilüferli koi göleti", "koi pond with lily pads", "#6f9fd8"],
      L: ["Taş fenerli patika", "stone path lined with stone lanterns", "#d8c49a"],
    },
    scene: {
      what: "cherry blossom shrine garden",
      place: "shrine garden",
      structure: "shrine garden structure",
      bullets: ["connected stone paths, steps and moss-covered garden walls", "continuous hillside, pond edge, rooftops and blossom canopy"],
      light: "one shared soft light source (spring morning sun)",
      identity: "lighting, blossoms, moss, roof tiles, water and shadows",
      cross: "A stone path may begin in one zone and continue into another; drifting cherry petals, garden walls, steps and light beams should flow naturally across the full composition.",
      bounds: "changes in ground material, wall corners, roof lines, shadow edges, garden paths, water edges and soft shifts in ambient lighting",
      style: "soft spring morning light",
      palette: "pastel pink-and-green",
      readAs: "cherry blossom shrine",
    },
  },

  {
    id: "coral-reef", variety: "Çift açılış",
    tr: "Mercan Resifi", artName: "Coral Reef",
    artGrid: [
      "SSSSTT",
      "SSSSTT",
      "WWWFFK",
      "WWWFFK",
      "WWWCCK",
      "RRRCCK",
    ],
    spec: { cols: 6, rows: 6, start: [2, 2], maxTech: 4, pieces: [7, 10], effortTarget: 38, t1Max: 0.45, decMin: 4, liveMin: 2.5, deepMin: 0, hiddenCount: 0 },
    puzzle: {
      grid: [
        "AAAAAA",
        "AAAAAA",
        "BBBBCC",
        "BBBBCC",
        "DDEFCC",
        "GGEFHH",
      ],
      clues: { A: [0, 3], B: [2, 0], C: [2, 5], D: [4, 1], E: [5, 2], F: [5, 3], G: [5, 1], H: [5, 5] },
      hidden: [],
    },
    zones: {
      S: ["Güneş ışınlarının süzüldüğü su yüzeyi", "sunlit water surface with shimmering light rays", "#a9e0ef"],
      T: ["Süzülen deniz kaplumbağası", "sea turtle gliding through open water", "#6f9fd8"],
      W: ["Mercan kaplı batık gemi", "coral-covered sunken wooden shipwreck", "#c9a271"],
      F: ["Renkli balık sürüsü", "school of colorful tropical fish", "#f2d16b"],
      K: ["Uzun yosun ormanı (kelp)", "tall swaying kelp forest", "#7fb98a"],
      C: ["Pembe mercan bahçesi, anemonlar", "pink coral garden with anemones and clownfish", "#f09bb0"],
      R: ["Açık hazine sandığıyla kumlu dip", "sandy seabed with an open treasure chest", "#e8d49a"],
    },
    scene: {
      what: "underwater coral reef",
      place: "reef",
      structure: "underwater reef structure",
      bullets: ["connected sandy seabed, rock ledges and coral shelves", "continuous kelp, bubbles, schools of fish and sunbeams drifting through the water"],
      light: "one shared lighting source (sunlight filtering down from the surface)",
      identity: "water depth, light rays, coral colors, sand, kelp and shadows",
      cross: "A rock ledge may begin in one zone and continue into another; kelp, coral, fish trails, bubbles and light rays should flow naturally across the full composition.",
      bounds: "changes in water depth, rock edges, coral clusters, sand ripples, shadow edges and soft shifts in underwater light",
      style: "shimmering sunlit underwater light",
      palette: "aqua-and-coral",
      readAs: "coral reef",
      horizon: "eye level",
      repeat: "natural",
    },
  },

  {
    id: "harvest-farm", variety: "Dik mi yatay mı",
    tr: "Hasat Çiftliği", artName: "Harvest Farm",
    artGrid: [
      "GGGWHH",
      "GGGWHH",
      "BBBWHH",
      "BBBOOO",
      "PPSOOO",
      "PPSYYY",
    ],
    spec: { cols: 7, rows: 7, start: [1, 1], maxTech: 4, pieces: [9, 12], effortTarget: 50, t1Max: 0.4, decMin: 5, liveMin: 2.7, deepMin: 0, hiddenCount: 1 },
    puzzle: {
      grid: [
        "AABBCCD",
        "AABBCCD",
        "AABBCCD",
        "EEBBCCF",
        "EEBBCCF",
        "EEBBGHF",
        "EEIIGHF",
      ],
      clues: { A: [1, 0], B: [0, 3], C: [1, 5], D: [2, 6], E: [6, 0], F: [3, 6], G: [5, 4], H: [5, 5], I: [6, 3] },
      hidden: ["B"],
    },
    zones: {
      G: ["Göçmen kazların uçtuğu sonbahar göğü", "autumn sky with a flock of migrating geese", "#f5d9a8"],
      W: ["Ahşap yel değirmeni", "wooden windmill with turning sails", "#c9a271"],
      H: ["Bacası tüten çiftlik evi", "farmhouse with a smoking chimney", "#9fb7c9"],
      B: ["Büyük kırmızı ahır", "big red barn with open doors", "#e0685a"],
      O: ["Sepetli elma bahçesi", "apple orchard with baskets of apples", "#8fc177"],
      P: ["Balkabağı tarlası", "pumpkin patch", "#f0a04b"],
      S: ["Sevimli korkuluk", "friendly scarecrow among corn stalks", "#9c7a54"],
      Y: ["Toprak yolda saman balyaları ve küçük traktör", "hay bales and a little tractor on a dirt road", "#f2d16b"],
    },
    scene: {
      what: "autumn harvest farm",
      place: "farm",
      structure: "farm structure",
      bullets: ["connected dirt roads, wooden fences and field rows", "continuous rolling hills, orchards, rooftops and hay fields"],
      light: "one shared warm lighting source (golden autumn afternoon sun)",
      identity: "lighting, crops, leaves, barn paint, wood and shadows",
      cross: "A dirt road may begin in one zone and continue into another; fences, crop rows, falling leaves and sun rays should flow naturally across the full composition.",
      bounds: "changes in field crops, fence lines, roof lines, shadow edges, dirt paths and soft shifts in ambient lighting",
      style: "golden autumn afternoon light",
      palette: "warm autumn",
      readAs: "harvest farm",
    },
  },

  {
    id: "candy-land", variety: "Nefes molası",
    tr: "Şeker Diyarı", artName: "Candy Land",
    artGrid: [
      "CCCRR",
      "LHHRR",
      "LHHUU",
      "LFFUU",
      "VVVVV",
    ],
    spec: { cols: 6, rows: 6, start: [1, 1], maxTech: 4, pieces: [7, 10], effortTarget: 32, t1Max: 0.5, decMin: 3, liveMin: 2.3, deepMin: 0, hiddenCount: 1 },
    puzzle: {
      grid: [
        "ABBCCD",
        "ABBCCD",
        "ABBCCD",
        "EEECCF",
        "EEEGGF",
        "EEEGGF",
      ],
      clues: { A: [1, 0], B: [2, 2], C: [3, 4], D: [2, 5], E: [3, 0], F: [5, 5], G: [5, 4] },
      hidden: ["E"],
    },
    zones: {
      C: ["Pamuk şeker bulutları", "cotton-candy clouds", "#f6c6de"],
      R: ["Jelibon tepesinin üstünde gökkuşağı", "rainbow over a gumdrop hill", "#b9a6d8"],
      L: ["Burgulu lolipop ağaçları", "swirly lollipop trees", "#f28b9b"],
      H: ["Krema çatılı zencefilli kurabiye ev", "gingerbread house with an icing roof", "#c98a5a"],
      U: ["Rengarenk süslü cupcake tepesi", "cupcake hill with rainbow sprinkles", "#f7e08a"],
      F: ["Baston şeker çit ve jelibon bahçesi", "candy-cane fence and gumdrop garden", "#8fd1b8"],
      V: ["Gofret köprülü çikolata nehri", "chocolate river with a wafer bridge", "#8b603f"],
    },
    scene: {
      what: "candy land",
      place: "candy land",
      structure: "candy land structure",
      bullets: ["connected candy paths, wafer bridges and frosting hills", "continuous chocolate river, sprinkles, gumdrops and sugar clouds"],
      light: "one shared bright lighting source (sunny afternoon)",
      identity: "lighting, frosting, sprinkles, candy colors, chocolate and shadows",
      cross: "A candy path may begin in one zone and continue into another; the chocolate river, frosting drips, sprinkles and sugar clouds should flow naturally across the full composition.",
      bounds: "changes in ground material, frosting edges, roof lines, shadow edges, candy paths and soft shifts in ambient lighting",
      style: "bright sunny light",
      palette: "sweet pastel",
      readAs: "candy land",
    },
  },

  {
    id: "desert-oasis", variety: "Gizli sayı",
    tr: "Çöl Vahası", artName: "Desert Oasis",
    artGrid: [
      "SSSSPPP",
      "SSSSPPP",
      "TTOOODD",
      "TTOOODD",
      "TTOOODD",
      "BBBCCCC",
      "BBBCCCC",
    ],
    spec: { cols: 7, rows: 7, start: [1, 1], maxTech: 4, pieces: [9, 12], effortTarget: 58, t1Max: 0.4, decMin: 6, liveMin: 2.8, deepMin: 0, hiddenCount: 1 },
    puzzle: {
      grid: [
        "AAABBBB",
        "AAACCCD",
        "AAACCCD",
        "EEECCCD",
        "EEECCCD",
        "FFFFGGH",
        "FFFFIIH",
      ],
      clues: { A: [0, 0], B: [0, 6], C: [3, 4], D: [3, 6], E: [3, 1], F: [6, 0], G: [5, 4], H: [6, 6], I: [6, 4] },
      hidden: ["F"],
    },
    zones: {
      S: ["Güneşli masmavi gök, süzülen şahin", "blazing blue sky with the sun and a soaring falcon", "#a9d8ef"],
      P: ["Ufukta piramitler", "pyramids on the distant horizon", "#e8c27a"],
      T: ["Halılı, çizgili pazar çadırları", "striped bazaar tents with hanging rugs", "#e0685a"],
      O: ["Palmiyelerle çevrili turkuaz vaha gölü", "turquoise oasis pool framed by palm trees", "#5fc0b8"],
      D: ["Kubbeli kumtaşı saray", "sandstone palace with domes", "#e9e1cf"],
      B: ["Toprak küplü baharat tezgahları", "spice market stalls with clay pots", "#9c7a54"],
      C: ["Altın kumullarda deve kervanı", "camel caravan crossing golden dunes", "#f2c14e"],
    },
    scene: {
      what: "desert oasis town",
      place: "oasis town",
      structure: "oasis town structure",
      bullets: ["connected sand paths, courtyard walls and palm-shaded plazas", "continuous dunes, rooftops, market awnings and horizon line"],
      light: "one shared warm lighting source (bright midday sun)",
      identity: "lighting, sand tones, fabrics, water, palm leaves and shadows",
      cross: "A sand path may begin in one zone and continue into another; dunes, palm fronds, awnings, caravan tracks and heat shimmer should flow naturally across the full composition.",
      bounds: "changes in ground material, wall corners, roof lines, shadow edges, dune ridges and soft shifts in ambient lighting",
      style: "bright warm desert light",
      palette: "sand-and-turquoise",
      readAs: "desert oasis",
    },
  },

  {
    id: "arctic-night", variety: "Çift açılış",
    tr: "Kutup Gecesi", artName: "Arctic Night",
    artGrid: [
      "AAAAMM",
      "AAAAMM",
      "GGIIIB",
      "GGIIIB",
      "LLLHHB",
      "LLLHHB",
    ],
    spec: { cols: 7, rows: 7, start: [2, 2], maxTech: 4, pieces: [9, 12], effortTarget: 64, t1Max: 0.35, decMin: 6, liveMin: 3, deepMin: 1, hiddenCount: 1 },
    puzzle: {
      grid: [
        "AABBBCC",
        "AABBBCC",
        "DDBBBCC",
        "DDBBBEE",
        "DDFFGEE",
        "HIFFGEE",
        "HIFFGJJ",
      ],
      clues: { A: [0, 1], B: [3, 3], C: [2, 5], D: [4, 1], E: [5, 5], F: [6, 3], G: [5, 4], H: [6, 0], I: [6, 1], J: [6, 5] },
      hidden: ["F"],
    },
    zones: {
      A: ["Yıldızlı gökte yeşil kuzey ışıkları", "green aurora ribbons over a starry sky", "#5fbf9a"],
      M: ["Dolunay ve parlayan yıldızlar", "full moon and twinkling stars", "#3f4a7a"],
      G: ["Buz sarkıtlı mavi buzul yamacı", "blue glacier slope with icicles", "#a9d8ef"],
      I: ["İçi sıcak ışıkla parlayan iglo köyü", "igloo village glowing warmly from inside", "#f5e6c8"],
      B: ["Donmuş şelale", "tall frozen waterfall", "#7fb8d8"],
      L: ["Buz balıkçısı kulübeli donmuş göl", "frozen lake with an ice-fishing hut", "#6f9fd8"],
      H: ["Fenerli husky kızak takımı", "husky sled team with lanterns", "#c9a271"],
    },
    scene: {
      what: "arctic night village",
      place: "arctic village",
      structure: "arctic landscape",
      bullets: ["connected snowfields, ice ridges and sled tracks", "continuous frozen shoreline, glacier walls and aurora-lit sky"],
      light: "one shared lighting source (aurora and moonlight, with warm glows from the igloos)",
      identity: "aurora glow, moonlight, ice tones, snow, warm lantern light and shadows",
      cross: "A sled track may begin in one zone and continue into another; snow drifts, ice ridges, aurora ribbons and lantern light should flow naturally across the full composition.",
      bounds: "changes in snow texture, ice edges, ridge lines, shadow edges, sled tracks and soft shifts in ambient lighting",
      style: "calm aurora night light",
      palette: "cool teal-and-indigo with warm accents",
      readAs: "arctic night",
      repeat: "natural",
    },
  },

  {
    id: "steampunk-sky-city", variety: "Dik mi yatay mı",
    tr: "Buharlı Gök Şehri", artName: "Steampunk Sky City",
    artGrid: [
      "SSSAAAA",
      "SSSAAAA",
      "KHHGGGD",
      "KHHGGGD",
      "KTTTTWD",
      "KRRMMWD",
      "LLLLLLL",
    ],
    spec: { cols: 8, rows: 8, start: [1, 1], maxTech: 4, pieces: [11, 15], effortTarget: 80, t1Max: 0.35, decMin: 7, liveMin: 3, deepMin: 1, hiddenCount: 2 },
    puzzle: {
      grid: [
        "ABBBBCCD",
        "ABBBBCCD",
        "AEEEECCD",
        "AFFGGCCD",
        "HHHGGCCD",
        "IIIGGJJD",
        "IIIGGJJD",
        "IIIGGKKD",
      ],
      clues: { A: [3, 0], B: [1, 2], C: [2, 5], D: [6, 7], E: [2, 2], F: [3, 2], G: [7, 4], H: [4, 1], I: [7, 0], J: [5, 6], K: [7, 6] },
      hidden: ["G","H"],
    },
    zones: {
      S: ["Pembe bulutlu gün batımı göğü", "sunset sky with pink clouds", "#f4a6a0"],
      A: ["Dev pirinç zeplin", "giant brass airship", "#d8b25e"],
      K: ["Uzun saat kulesi", "tall clock tower", "#8e7aa8"],
      H: ["Küçük sıcak hava balonları", "little hot-air balloons", "#e0685a"],
      G: ["Buhar tüten bacalı dişli fabrikası", "gear factory with steaming chimneys", "#b0824d"],
      D: ["Vinçli zeplin iskele kulesi", "airship docking tower with a crane", "#6b6f78"],
      T: ["Viyadük üstünde buharlı tren", "steam train crossing an elevated viaduct", "#3f5f7f"],
      W: ["Borulu bakır buhar kazanı", "copper steam boiler with pipes", "#e39a5a"],
      R: ["Borulu çatılar ve güvercinler", "rooftops with pipes and pigeons", "#a9786a"],
      M: ["Mucit pazarı tezgahları", "inventors' market stalls", "#8fc177"],
      L: ["Fenerli arnavut kaldırımı sokak", "lamp-lit cobblestone street", "#f2d16b"],
    },
    scene: {
      what: "steampunk sky city",
      place: "sky city",
      structure: "steampunk city structure",
      bullets: ["connected brass walkways, viaducts, rooftops and pipes", "continuous chimney smoke, cables, gears and street lamps"],
      light: "one shared warm lighting source (sunset sun)",
      identity: "sunset light, brass and copper tones, steam, painted awnings, lamp glow and shadows",
      cross: "A pipe may begin in one zone and continue into another; viaducts, cables, steam clouds, rooftops and lamp light should flow naturally across the full composition.",
      bounds: "changes in building material, wall corners, roof lines, shadow edges, walkways and soft shifts in ambient lighting",
      style: "warm sunset light",
      palette: "brass-copper-and-rose",
      readAs: "steampunk sky city",
    },
  },

  {
    id: "bookshop-cafe", variety: "Nefes molası",
    tr: "Kitapçı Kafe", artName: "Bookshop Café",
    artGrid: [
      "BWWWWS",
      "BWWWWS",
      "BAAFFS",
      "BAAFFS",
      "CCCRRP",
      "CCCRRP",
    ],
    spec: { cols: 7, rows: 7, start: [1, 1], maxTech: 4, pieces: [9, 12], effortTarget: 50, t1Max: 0.4, decMin: 5, liveMin: 2.7, deepMin: 0, hiddenCount: 1 },
    puzzle: {
      grid: [
        "AAAABBB",
        "AAAABBB",
        "CCCDBBB",
        "CCCDEFF",
        "GHHHEFF",
        "GIIIEFF",
        "GIIIEJJ",
      ],
      clues: { A: [1, 0], B: [0, 6], C: [2, 1], D: [2, 3], E: [4, 4], F: [4, 6], G: [4, 0], H: [4, 2], I: [6, 1], J: [6, 5] },
      hidden: ["A"],
    },
    zones: {
      B: ["Uzun ahşap kitap rafı", "tall wooden bookshelf", "#b0824d"],
      W: ["Yağmurlu sokağa bakan büyük kemerli pencere", "big arched window looking out on a rainy street", "#6f9fd8"],
      S: ["Kitap duvarına dayalı merdiven", "rolling ladder against a wall of books", "#8e7aa8"],
      A: ["Üstünde kedi uyuyan okuma koltuğu", "reading armchair with a sleeping cat", "#7fb98a"],
      F: ["Çıtırdayan şömine", "crackling fireplace", "#f0a04b"],
      C: ["Espresso makineli kafe tezgahı", "café counter with an espresso machine", "#d8b25e"],
      R: ["Sehpalı yumuşak halı, çay fincanları", "soft rug with a coffee table and teacups", "#e0685a"],
      P: ["Saksı bitkisi ve pasta standı", "potted plant and a pastry stand", "#8fc177"],
    },
    scene: {
      what: "bookshop café interior",
      place: "bookshop café",
      structure: "room structure",
      bullets: ["connected wooden floorboards, wall paneling and shelves", "continuous ceiling beams, hanging lamps, rugs and trailing plants"],
      light: "one shared warm lighting source (fireplace and lamp glow, rainy blue light from the window)",
      identity: "lamp and fire light, wood tones, book spines, upholstery, rain light and shadows",
      cross: "A shelf may begin in one zone and continue into another; floorboards, rugs, trailing plants, steam from cups and light pools should flow naturally across the full composition.",
      bounds: "changes in floor material, wall corners, shelf edges, shadow edges, rugs and soft shifts in ambient lighting",
      style: "warm lamplight with cool rainy window light",
      palette: "cozy wood-and-amber",
      readAs: "cozy bookshop café",
      horizon: "eye level",
    },
  },

  {
    id: "pirate-cove", variety: "Gizli sayı",
    tr: "Korsan Koyu", artName: "Pirate Cove",
    artGrid: [
      "YYVVVKK",
      "YYVVVKK",
      "SSSSPKK",
      "SSSSPCC",
      "SSSSPCC",
      "RRDDDBB",
      "RRDDDBB",
    ],
    spec: { cols: 8, rows: 8, start: [1, 1], maxTech: 4, pieces: [11, 15], effortTarget: 86, t1Max: 0.33, decMin: 8, liveMin: 3, deepMin: 1, hiddenCount: 2 },
    puzzle: {
      grid: [
        "AABBBCDE",
        "AAFGGCDE",
        "AAFGGCDE",
        "HHFGGCDE",
        "HHFGGCDE",
        "IIFGGCDJ",
        "IIFGGCKJ",
        "IILLLCKJ",
      ],
      clues: { A: [0, 1], B: [0, 4], C: [2, 5], D: [5, 6], E: [0, 7], F: [5, 2], G: [6, 4], H: [4, 1], I: [5, 1], J: [5, 7], K: [6, 6], L: [7, 2] },
      hidden: ["I","K"],
    },
    zones: {
      Y: ["Papağanların uçtuğu parlak gök", "bright sky with flying parrots", "#a9d8ef"],
      V: ["Duman tüten volkan adası", "volcano island with a thin plume of smoke", "#b9785a"],
      K: ["Şelaleli orman yamacı", "jungle cliff with a waterfall", "#4f9a6a"],
      S: ["Koyda demirli korsan gemisi", "pirate ship anchored in the bay", "#5b8fd0"],
      P: ["Uzun palmiye ağacı", "tall leaning palm tree", "#b5d86a"],
      C: ["Parıldayan hazineli deniz mağarası", "sea cave with glittering treasure", "#3f4a7a"],
      R: ["Yengeçli kayalar ve gelgit havuzları", "rocks with crabs and tide pools", "#9aa3a8"],
      D: ["Kayıklı ahşap iskele", "wooden dock with a rowboat", "#c9a271"],
      B: ["Hazine sandıklı kumsal", "sandy beach with a treasure chest", "#f2d16b"],
    },
    scene: {
      what: "tropical pirate cove",
      place: "cove",
      structure: "island cove structure",
      bullets: ["connected sandy shores, rocky ledges and wooden docks", "continuous shoreline, jungle hills, sea surface and horizon"],
      light: "one shared warm lighting source (bright tropical noon sun)",
      identity: "sea depth, sand, jungle greens, volcanic rock, wood and shadows",
      cross: "A dock may begin in one zone and continue into another; the shoreline, waves, jungle vines, ropes and sun sparkles should flow naturally across the full composition.",
      bounds: "changes in shore material, cliff edges, waterlines, shadow edges, sandy paths and soft shifts in ambient lighting",
      style: "bright tropical light",
      palette: "turquoise-and-jungle-green",
      readAs: "pirate cove",
      repeat: "natural",
    },
  },

  {
    id: "dinosaur-valley", variety: "Çift açılış",
    tr: "Dinozor Vadisi", artName: "Dinosaur Valley",
    artGrid: [
      "PPPPVVVV",
      "PPPPVVVV",
      "BBWWVVVV",
      "BBWWTTTG",
      "BBWWTTTG",
      "BBRRTTTG",
      "EERRXXXX",
      "EERRXXXX",
    ],
    spec: { cols: 8, rows: 8, start: [2, 2], maxTech: 4, pieces: [11, 15], effortTarget: 92, t1Max: 0.3, decMin: 9, liveMin: 3.1, deepMin: 1, hiddenCount: 1 },
    puzzle: {
      grid: [
        "ABBBBBCC",
        "ABBBBBCC",
        "ADDDDDDE",
        "FFFFGGGE",
        "FFFFGGGE",
        "HHHHHHHH",
        "IJJKKKLL",
        "IJJKKKLL",
      ],
      clues: { A: [1, 0], B: [1, 3], C: [1, 7], D: [2, 6], E: [2, 7], F: [3, 1], G: [4, 5], H: [5, 2], I: [7, 0], J: [7, 1], K: [6, 4], L: [7, 7] },
      hidden: ["H"],
    },
    zones: {
      P: ["Pterozorların süzüldüğü gök", "hazy sky with gliding pterosaurs", "#f5d9a8"],
      V: ["Lav fışkırtan volkan", "erupting volcano with glowing lava", "#e0685a"],
      B: ["Ağaç tepesinden yiyen uzun boyunlu dinozor", "long-neck dinosaur eating from treetops", "#8fc177"],
      W: ["Yosunlu kayalıktan dökülen şelale", "waterfall over mossy cliffs", "#a9d8ef"],
      T: ["Dev eğrelti otları arasında sevimli T-rex", "friendly T-rex among giant ferns", "#5f9a5a"],
      G: ["Fokurdayan sıcak su kaynağı, gayzer", "bubbling hot spring with a geyser", "#cfe8f5"],
      R: ["Kıvrılan nehir", "winding river", "#5b8fd0"],
      E: ["Benekli yumurtalı yuva", "nest with speckled eggs", "#d8c49a"],
      X: ["Çayırda triceratops sürüsü", "triceratops herd on a grassy plain", "#c9d86a"],
    },
    scene: {
      what: "prehistoric dinosaur valley",
      place: "valley",
      structure: "valley landscape",
      bullets: ["connected riverbanks, rocky ledges and fern-covered slopes", "continuous jungle canopy, river, volcano slopes and horizon"],
      light: "one shared warm lighting source (hazy late-afternoon sun with a soft volcanic glow)",
      identity: "lighting, foliage greens, rock tones, water, lava glow, mist and shadows",
      cross: "The river may begin in one zone and continue into another; ferns, rock ledges, mist, steam and sun rays should flow naturally across the full composition.",
      bounds: "changes in ground material, cliff edges, foliage lines, shadow edges, riverbanks and soft shifts in ambient lighting",
      style: "warm hazy afternoon light",
      palette: "lush green-and-amber",
      readAs: "dinosaur valley",
      repeat: "natural",
    },
  },

  {
    id: "mushroom-village", variety: "Dik mi yatay mı",
    tr: "Mantar Ormanı Peri Köyü", artName: "Mushroom Village",
    artGrid: [
      "FFFMMT",
      "LLLMMT",
      "LLLHHT",
      "WWGHHT",
      "WWGBBB",
      "RRGBBB",
    ],
    spec: { cols: 8, rows: 9, start: [1, 1], maxTech: 4, pieceStyle: "big", pieces: [10, 13], effortTarget: 100, t1Max: 0.3, decMin: 9, liveMin: 3, deepMin: 2, cornerMax: 0.35, hiddenCount: 1, lockCount: 1 },
    puzzle: {
      grid: [
        "AAAABBCD",
        "AAAABBCD",
        "AAAABBCD",
        "AAAABBCD",
        "EEEFBBCD",
        "EEEFGHCD",
        "EEEFGHCI",
        "EEEFGHJI",
        "KKKKKKJI",
      ],
      clues: { A: [2, 2], B: [1, 5], C: [0, 6], D: [1, 7], E: [6, 0], F: [5, 3], G: [6, 4], H: [6, 5], I: [8, 7], J: [8, 6], K: [8, 2] },
      hidden: ["A"],
      locks: { G: 3 },
    },
    zones: {
      F: ["Ateşböcekli alacakaranlık yaprakları", "dusk canopy full of fireflies", "#6a5a9a"],
      M: ["Yaprakların arasından hilal ay", "crescent moon peeking through the leaves", "#b9a6d8"],
      T: ["Fenerli uzun ağaç", "tall tree hung with glowing lanterns", "#5f9a7a"],
      L: ["Yuvarlak pencereli dev kırmızı mantar ev", "giant red mushroom house with round windows", "#e0685a"],
      H: ["Perilerin dans ettiği mantar halkası", "toadstool ring with dancing fairies", "#f2a7c3"],
      W: ["Kurbağalı, nilüferli dere", "stream with lily pads and a frog", "#6fb8d8"],
      G: ["Salyangozlu uzun çan çiçekleri", "tall bellflowers with a snail", "#b48ad8"],
      B: ["Oyuk kütük köprü", "hollow log bridge", "#b0824d"],
      R: ["Parıldayan çakıl taşı yolu", "glowing pebble path", "#f2d16b"],
    },
    scene: {
      what: "mushroom forest fairy village",
      place: "fairy village",
      structure: "forest village structure",
      bullets: ["connected pebble paths, roots, stepping stones and log bridges", "continuous forest canopy, stream, glowing lanterns and firefly trails"],
      light: "one shared lighting source (soft dusk light with warm lantern and firefly glow)",
      identity: "dusk light, lantern glow, mushroom caps, flowers, water and shadows",
      cross: "A pebble path may begin in one zone and continue into another; roots, vines, the stream, firefly trails and lantern light should flow naturally across the full composition.",
      bounds: "changes in ground material, root lines, mushroom caps, shadow edges, paths and soft shifts in ambient lighting",
      style: "magical dusk light",
      palette: "twilight purple-and-moss",
      readAs: "mushroom fairy village",
    },
  },

  {
    id: "crystal-cave", variety: "Gizli sayı",
    tr: "Kristal Mağarası", artName: "Crystal Cave",
    artGrid: [
      "SSSSEEE",
      "CCCWEEE",
      "CCCWGGM",
      "CCCWGGM",
      "TTTTGGM",
      "LLLLLVV",
      "LLLLLVV",
    ],
    spec: { cols: 7, rows: 10, start: [1, 1], maxTech: 4, pieceStyle: "big", pieces: [10, 13], effortTarget: 106, t1Max: 0.3, decMin: 9, liveMin: 3, deepMin: 2, cornerMax: 0.35, hiddenCount: 1, lockCount: 1 },
    puzzle: {
      grid: [
        "AABCDEE",
        "AABCDEE",
        "AABCDEE",
        "FFBCDGH",
        "FFBCDGH",
        "FFBCIGH",
        "JJBCIGH",
        "JJKCIGH",
        "JJKCIGH",
        "LLLLLLL",
      ],
      clues: { A: [1, 1], B: [3, 2], C: [3, 3], D: [2, 4], E: [1, 6], F: [4, 1], G: [6, 5], H: [7, 6], I: [7, 4], J: [8, 1], K: [7, 2], L: [9, 5] },
      hidden: ["B"],
      locks: { D: 3 },
    },
    zones: {
      S: ["Işıl ışıl solucanlı sarkıt tavan", "stalactite ceiling with glowworms", "#3f4a7a"],
      E: ["Fenerli, ahşap destekli maden girişi", "mine entrance with lanterns and wooden beams", "#8b603f"],
      C: ["Işıldayan dev kristal kümesi", "giant glowing crystal cluster", "#b48ad8"],
      W: ["Yeraltı şelalesi", "underground waterfall", "#6fb8d8"],
      G: ["Kamp ateşli, kazmalı madenci kampı", "miners' camp with a campfire and pickaxes", "#f0a04b"],
      M: ["Mavi ışıldayan mantarlar", "glowing blue mushrooms", "#5fc0b8"],
      T: ["Mücevher dolu raylı maden arabası", "minecart full of gems on rails", "#8e8a80"],
      L: ["Kristalleri yansıtan durgun yeraltı gölü", "still underground lake reflecting the crystals", "#4a6fb0"],
      V: ["Altın ve mücevher dolu hazine odası", "treasure vault with gold coins and gems", "#f2d16b"],
    },
    scene: {
      what: "crystal cave mine",
      place: "cave",
      structure: "cave structure",
      bullets: ["connected rock ledges, mine rails, wooden supports and ladders", "continuous cave walls, ceiling, underground water and crystal veins"],
      light: "one shared lighting source (glowing crystals with warm lantern and campfire light)",
      identity: "crystal glow, lantern light, rock tones, water reflections, gold and shadows",
      cross: "A mine rail may begin in one zone and continue into another; crystal veins, wooden beams, water, glowworms and light beams should flow naturally across the full composition.",
      bounds: "changes in rock material, cave wall edges, ledges, shadow edges, water edges and soft shifts in ambient lighting",
      style: "glowing crystal light",
      palette: "amethyst-and-teal with warm gold",
      readAs: "crystal cave",
      horizon: "eye level",
      repeat: "natural",
    },
  },

  {
    id: "carnival-night", variety: "Nefes molası",
    tr: "Lunapark Gecesi", artName: "Carnival Night",
    artGrid: [
      "FFWWW",
      "FFWWW",
      "CCWWW",
      "CCTTR",
      "SSTTR",
    ],
    spec: { cols: 8, rows: 8, start: [1, 1], maxTech: 4, pieces: [11, 15], effortTarget: 78, t1Max: 0.35, decMin: 7, liveMin: 3, deepMin: 1, hiddenCount: 2 },
    puzzle: {
      grid: [
        "AAABBBCC",
        "AAABBBCC",
        "AAABBBCC",
        "DDDDDDCC",
        "EEFFGHCC",
        "EEFFGHII",
        "EEFFGJII",
        "EEKKKJII",
      ],
      clues: { A: [0, 0], B: [0, 5], C: [4, 6], D: [3, 4], E: [6, 1], F: [4, 3], G: [5, 4], H: [4, 5], I: [6, 6], J: [6, 5], K: [7, 3] },
      hidden: ["B","I"],
    },
    zones: {
      F: ["Havai fişekli gece göğü", "night sky with fireworks", "#3f4a7a"],
      W: ["Işıklı dönme dolap", "glowing Ferris wheel", "#f2d16b"],
      C: ["Boyalı atlı atlıkarınca", "carousel with painted horses", "#f2a7c3"],
      T: ["Çizgili sirk çadırı", "striped circus tent", "#e0685a"],
      R: ["Pamuk şeker arabası", "cotton candy cart", "#b9a6d8"],
      S: ["Patlamış mısır standı, balon satıcısı", "popcorn stand and a balloon seller", "#f0a04b"],
    },
    scene: {
      what: "night carnival",
      place: "carnival",
      structure: "fairground structure",
      bullets: ["connected boardwalks, fairground paths and fences", "continuous string lights, bunting, tents and ride structures"],
      light: "one shared lighting source (warm fairground lights under a night sky)",
      identity: "string lights, warm glows, striped fabrics, painted wood and shadows",
      cross: "A string of lights may begin in one zone and continue into another; paths, bunting, balloons and light glows should flow naturally across the full composition.",
      bounds: "changes in ground material, tent edges, ride silhouettes, shadow edges, paths and soft shifts in ambient lighting",
      style: "warm festive night light",
      palette: "candy-bright on deep blue",
      readAs: "carnival night",
    },
  },

  {
    id: "toy-workshop", variety: "Çift açılış · Kesişim ve eleme",
    tr: "Oyuncak Atölyesi", artName: "Toy Workshop",
    artGrid: [
      "AAAAACWW",
      "AAAAACWW",
      "SSSDDDWW",
      "SSSDDDTT",
      "PPHDDDTT",
      "PPHBBBTT",
      "NNHBBBRR",
      "NNXXXXRR",
    ],
    spec: { cols: 8, rows: 9, start: [2, 2], maxTech: 4, pieceStyle: "big", pieces: [10, 13], effortTarget: 112, t1Max: 0.3, decMin: 9, liveMin: 3, deepMin: 2, cornerMax: 0.35, hiddenCount: 1, lockCount: 1 },
    puzzle: {
      grid: [
        "ABCCDEFG",
        "ABCCDEFG",
        "ABCCDEFG",
        "ABCCDEFG",
        "ABCCDEFG",
        "AHCCIEFG",
        "AHCCIEFG",
        "AHJJIEFK",
        "AHJJLLLK",
      ],
      clues: { A: [1, 0], B: [2, 1], C: [1, 3], D: [1, 4], E: [4, 5], F: [5, 6], G: [3, 7], H: [7, 1], I: [6, 4], J: [7, 3], K: [7, 7], L: [8, 5] },
      hidden: ["F"],
      locks: { G: 4 },
    },
    zones: {
      A: ["Tavan kirişlerinden sarkan model uçaklar ve uçurtmalar", "model airplanes and kites hanging from wooden ceiling beams", "#d8c49a"],
      C: ["Guguklu saat", "cuckoo clock", "#8b603f"],
      W: ["Akşam bahçesine bakan kemerli pencere", "arched window looking out on an evening garden", "#6f9fd8"],
      S: ["Oyuncak ayı ve bebek rafları", "shelves full of teddy bears and dolls", "#9c6b3f"],
      D: ["Büyük Viktorya tarzı oyuncak ev", "big Victorian dollhouse", "#f2a7c3"],
      T: ["Kırmızı perdeli kukla tiyatrosu", "puppet theater with red curtains", "#e0685a"],
      P: ["Boya kutuları ve fırçalar", "paint pots and brushes", "#7fb98a"],
      H: ["Ahşap sallanan at", "painted wooden rocking horse", "#e07a5a"],
      B: ["Aletli tezgah, yarım kalmış oyuncak robot", "workbench with tools and a half-built toy robot", "#8a9aa8"],
      N: ["Üst üste renkli oyuncak bloklar", "stacked colorful toy blocks", "#f2d16b"],
      R: ["Yün sepetinde uyuyan kedi", "cat sleeping in a yarn basket", "#b9a6d8"],
      X: ["Yerdeki raylarda ahşap oyuncak tren", "wooden toy train on a track across the floor", "#5fc0b8"],
    },
    scene: {
      what: "toy maker's workshop interior",
      place: "workshop",
      structure: "room structure",
      bullets: ["connected wooden floorboards, workbenches and wall shelves", "continuous ceiling beams, strings of toys, shelves and window frames"],
      light: "one shared warm lighting source (lamplight with soft evening light from the window)",
      identity: "lamplight, wood tones, painted toys, fabrics, paint colors and shadows",
      cross: "A shelf may begin in one zone and continue into another; floorboards, toy train tracks, hanging strings, wood shavings and light pools should flow naturally across the full composition.",
      bounds: "changes in floor material, wall corners, shelf edges, shadow edges, rugs and soft shifts in ambient lighting",
      style: "warm golden lamplight",
      palette: "cozy wood with toy-bright accents",
      readAs: "toy workshop",
      horizon: "eye level",
    },
  },

  {
    id: "savanna-sunset", variety: "Gizli sayı",
    tr: "Savana Gün Batımı", artName: "Savanna Sunset",
    artGrid: [
      "SSSSAAA",
      "SSSSAAA",
      "GLLLAAA",
      "GLLLWWW",
      "GZZZWWW",
      "MMJJJFF",
      "MMJJJFF",
    ],
    spec: { cols: 8, rows: 10, start: [1, 1], maxTech: 4, pieceStyle: "big", pieces: [11, 14], effortTarget: 118, t1Max: 0.3, decMin: 10, liveMin: 3, deepMin: 2, cornerMax: 0.35, hiddenCount: 1, lockCount: 1 },
    puzzle: {
      grid: [
        "AAABCDEF",
        "AAABCDEF",
        "AAABCDEF",
        "GGGBCDEF",
        "GGGBCDEF",
        "GGGBHDEF",
        "IIIJHDEK",
        "IIIJHDEK",
        "IIIJHLEK",
        "MMMMHLEK",
      ],
      clues: { A: [0, 1], B: [1, 3], C: [3, 4], D: [4, 5], E: [7, 6], F: [4, 7], G: [4, 1], H: [7, 4], I: [7, 1], J: [7, 3], K: [7, 7], L: [8, 5], M: [9, 2] },
      hidden: ["I"],
      locks: { E: 2 },
    },
    zones: {
      S: ["Dev güneşli altın gün batımı göğü", "golden sunset sky with a huge setting sun", "#f7c96b"],
      A: ["Kuş yuvalı akasya ağacı", "acacia tree with weaver-bird nests", "#d9824e"],
      G: ["Uzun zürafa", "tall giraffe", "#e0a040"],
      L: ["Kayalık çıkıntıda dinlenen aslanlar", "lions resting on a rocky outcrop", "#8a7a6a"],
      W: ["Fillerin su içtiği gölet", "waterhole with elephants drinking", "#6f9fd8"],
      Z: ["Zebra sürüsü", "herd of zebras", "#dcd6c8"],
      M: ["Uzun otlar arasında mirketler", "meerkats standing in tall grass", "#c9d86a"],
      J: ["Cipli, çadırlı safari kampı", "safari camp with a jeep and canvas tents", "#8fa05a"],
      F: ["Su kıyısında flamingolar", "flamingos at the water's edge", "#f2a7c3"],
    },
    scene: {
      what: "golden-hour savanna",
      place: "savanna",
      structure: "savanna landscape",
      bullets: ["connected grassland, dirt trails and rocky outcrops", "continuous horizon, tall grass, waterhole edge and acacia silhouettes"],
      light: "one shared warm lighting source (low golden-hour sun)",
      identity: "golden light, grass tones, earth, water reflections, animal silhouettes and long shadows",
      cross: "A dirt trail may begin in one zone and continue into another; tall grass, long shadows, dust, birds and sun glow should flow naturally across the full composition.",
      bounds: "changes in ground material, rock edges, grass lines, shadow edges, trails and soft shifts in ambient lighting",
      style: "golden-hour light",
      palette: "sunset gold-and-olive",
      readAs: "savanna sunset",
      repeat: "natural",
    },
  },

  {
    id: "moon-base", variety: "Çok seçenekli kararlar",
    tr: "Ay Üssü", artName: "Moon Base",
    artGrid: [
      "EEEEERPP",
      "EEEEERPP",
      "OODDDRPP",
      "OODDDRHH",
      "SSDDDRHH",
      "SSGGVVVT",
      "CCGGVVVT",
      "CCLLLLLT",
    ],
    spec: { cols: 8, rows: 10, start: [1, 1], maxTech: 4, pieceStyle: "big", pieces: [11, 14], effortTarget: 124, t1Max: 0.3, decMin: 10, liveMin: 3, deepMin: 2, cornerMax: 0.35, hiddenCount: 2, lockCount: 1 },
    puzzle: {
      grid: [
        "ABCCCCCD",
        "ABEFFGHD",
        "ABEFFGHD",
        "ABEFFGHD",
        "IBEFFGHD",
        "IBEFFJHK",
        "ILEMMJHK",
        "ILEMMJHK",
        "ILEMMJHK",
        "NNEMMJHK",
      ],
      clues: { A: [1, 0], B: [2, 1], C: [0, 3], D: [1, 7], E: [7, 2], F: [2, 4], G: [2, 5], H: [2, 6], I: [8, 0], J: [6, 5], K: [7, 7], L: [7, 1], M: [7, 3], N: [9, 0] },
      hidden: ["K","L"],
      locks: { F: 3 },
    },
    zones: {
      E: ["Dünya'nın doğduğu yıldızlı uzay", "starry space with the Earth rising", "#3f4a7a"],
      R: ["Fırlatma kulesinde uzun roket", "tall rocket on its launch tower", "#e0685a"],
      P: ["Halkalı gezegen ve kuyruklu yıldız", "ringed planet and a comet", "#b9a6d8"],
      O: ["Büyük teleskoplu gözlemevi", "observatory with a big telescope", "#9aa3a8"],
      D: ["Işıklı pencereli ana yaşam kubbeleri", "main habitat domes with glowing windows", "#f2d16b"],
      H: ["Uydu çanağı anteni", "satellite dish antenna", "#cfd8dc"],
      S: ["Güneş paneli dizisi", "solar panel array", "#4a6fb0"],
      G: ["Bitkili sera kubbesi", "greenhouse dome full of plants", "#8fc177"],
      V: ["Astronotlu ay aracı", "moon rover with astronauts", "#6fb8d8"],
      T: ["Ay iniş modülü", "lunar landing module", "#d8b25e"],
      C: ["Ay yürüyüşü yapan astronotlar", "astronauts on a bouncy moonwalk", "#c6c0e0"],
      L: ["Ayak izli kraterli ay yüzeyi", "cratered lunar ground with footprints", "#a8a4a0"],
    },
    scene: {
      what: "moon base",
      place: "moon base",
      structure: "lunar base structure",
      bullets: ["connected walkways, tubes, landing pads and airlocks", "continuous lunar ground, crater rims, cables and antenna masts"],
      light: "one shared lighting source (bright sunlight from one side, warm glow from the habitat windows)",
      identity: "starlight, habitat glow, metal tones, solar panel blue, regolith gray and shadows",
      cross: "A walkway tube may begin in one zone and continue into another; cables, footprints, crater rims, antenna masts and light beams should flow naturally across the full composition.",
      bounds: "changes in ground material, dome edges, crater rims, shadow edges, walkways and soft shifts in ambient lighting",
      style: "crisp space light with warm window glow",
      palette: "deep-space blue with warm accents",
      readAs: "moon base",
    },
  },

  {
    id: "haunted-manor", variety: "Çift gizli sayı",
    tr: "Perili Köşk", artName: "Haunted Manor",
    artGrid: [
      "MMHHHB",
      "MMHHHB",
      "TTHHHB",
      "TTGGPP",
      "FFGGPP",
      "FFCCPP",
    ],
    spec: { cols: 7, rows: 10, start: [1, 1], maxTech: 4, pieceStyle: "big", pieces: [10, 13], effortTarget: 114, t1Max: 0.3, decMin: 9, liveMin: 3, deepMin: 2, cornerMax: 0.35, hiddenCount: 2, lockCount: 1 },
    puzzle: {
      grid: [
        "ABCCDDD",
        "ABCCDDD",
        "ABEFDDD",
        "ABEFDDD",
        "AGEFDDD",
        "AGEFHHI",
        "AGEFHHI",
        "AGEJHHI",
        "AGEJHHI",
        "AGEJKKI",
      ],
      clues: { A: [1, 0], B: [2, 1], C: [0, 2], D: [3, 4], E: [3, 2], F: [4, 3], G: [8, 1], H: [6, 4], I: [6, 6], J: [8, 3], K: [9, 5] },
      hidden: ["E","H"],
      locks: { D: 2 },
    },
    zones: {
      M: ["Yarasalı dolunay", "big full moon with little bats", "#f2d16b"],
      H: ["Pencereleri parlayan eğri büğrü perili köşk", "crooked haunted manor with glowing windows", "#6a5a9a"],
      B: ["Baykuşlu boğumlu ağaç", "gnarled tree with an owl", "#3f4a7a"],
      T: ["Sevimli hayaletli mezar taşları", "cute tombstones with friendly ghosts", "#9aa3a8"],
      G: ["Balkabağı fenerli demir kapı", "iron gate lined with jack-o'-lanterns", "#f0a04b"],
      P: ["Sarmaşıklı balkabağı tarlası", "pumpkin patch with curly vines", "#7a9a5a"],
      F: ["Fokurdayan cadı kazanı", "bubbling witch's cauldron", "#8fd18a"],
      C: ["Şekerlemelerle dolu fenerli patika", "lantern-lit path scattered with candy", "#b9a6d8"],
    },
    scene: {
      what: "cute-spooky Halloween manor",
      place: "manor grounds",
      structure: "manor grounds structure",
      bullets: ["connected garden paths, iron fences and stone walls", "continuous hillside, gnarled trees, rooftops and drifting mist"],
      light: "one shared lighting source (full moonlight with warm pumpkin and window glows)",
      identity: "moonlight, pumpkin glow, purple mist, stone, foliage and shadows",
      cross: "A garden path may begin in one zone and continue into another; the iron fence, mist, vines, bats and lantern light should flow naturally across the full composition.",
      bounds: "changes in ground material, fence lines, roof lines, shadow edges, paths and soft shifts in ambient lighting",
      style: "friendly moonlit night light",
      palette: "purple-and-pumpkin",
      readAs: "haunted manor",
    },
  },

  {
    id: "viking-fjord", variety: "Çift açılış",
    tr: "Viking Fiyortu", artName: "Viking Fjord",
    artGrid: [
      "SSSMMMW",
      "SSSMMMW",
      "TLLLLHW",
      "TLLLLHW",
      "TFFKKHD",
      "BBBBBBD",
      "BBBBBBD",
    ],
    spec: { cols: 8, rows: 10, start: [0, 0], openTech: 3, calm: 0, maxTech: 4, pieceStyle: "big", pieces: [11, 14], effortTarget: 128, t1Max: 0.3, decMin: 10, liveMin: 3, deepMin: 3, cornerMax: 0.35, hiddenCount: 1, lockCount: 1 },
    puzzle: {
      grid: [
        "AAAAAABB",
        "CDEFFGBB",
        "CDEFFGBB",
        "CDEFFGHH",
        "CDEFFGHH",
        "CDEIIGHH",
        "CDEIIGHH",
        "CDEIIJHH",
        "KKKIIJLL",
        "KKKIIJLL",
      ],
      clues: { A: [0, 4], B: [1, 7], C: [6, 0], D: [3, 1], E: [4, 2], F: [2, 4], G: [5, 5], H: [6, 7], I: [8, 4], J: [8, 5], K: [8, 1], L: [8, 6] },
      hidden: ["G"],
      locks: { H: 5 },
    },
    zones: {
      S: ["Martılı sisli şafak göğü", "misty dawn sky with seabirds", "#f2c4b0"],
      M: ["Karlı dağ zirveleri", "snowy mountain peaks", "#cfe8f5"],
      W: ["Kayalıktan dökülen şelale", "waterfall tumbling down the cliff", "#6fb8d8"],
      T: ["Ahşap gözetleme kulesi", "wooden lookout tower", "#8b603f"],
      L: ["Çim çatılı, ejder başlı büyük uzun ev", "great longhouse with a turf roof and carved dragon heads", "#8fc177"],
      H: ["Közleri parlayan demirci ocağı", "blacksmith's forge with glowing embers", "#e0685a"],
      F: ["Koyun ağılı", "sheep pen", "#e8e0c8"],
      K: ["Balık kurutma sehpaları", "fish drying racks", "#d8b25e"],
      D: ["Direkler üstünde balıkçı kulübesi", "fishing hut on stilts", "#c9a271"],
      B: ["Uzun gemili sakin fiyort suyu", "calm fjord water with longships", "#4a6fb0"],
    },
    scene: {
      what: "Viking fjord village",
      place: "fjord village",
      structure: "fjord village structure",
      bullets: ["connected wooden boardwalks, stone steps and turf-roofed buildings", "continuous cliffs, shoreline, water surface and mountain ridge"],
      light: "one shared soft lighting source (misty sunrise light)",
      identity: "dawn light, mist, turf greens, wood tones, forge glow, water and shadows",
      cross: "A boardwalk may begin in one zone and continue into another; the shoreline, mist, smoke, ropes and the waterfall stream should flow naturally across the full composition.",
      bounds: "changes in ground material, cliff edges, roof lines, shadow edges, boardwalks and soft shifts in ambient lighting",
      style: "soft misty sunrise light",
      palette: "cool fjord blue with warm wood",
      readAs: "Viking fjord",
    },
  },

  {
    id: "sky-islands", variety: "Gizli sayı · Kesişim ve eleme",
    tr: "Gökyüzü Adaları", artName: "Sky Islands",
    artGrid: [
      "AAABBBBC",
      "AAABBBBC",
      "DDEEEEFC",
      "DDEEEEFC",
      "GGEEEEFH",
      "GGIIIIIH",
      "JJLLKKKH",
      "JJLLKKKH",
    ],
    spec: { cols: 8, rows: 10, start: [0, 0], openTech: 3, calm: 0, maxTech: 4, pieceStyle: "big", pieces: [11, 14], effortTarget: 134, t1Max: 0.3, decMin: 10, liveMin: 3, deepMin: 3, cornerMax: 0.35, hiddenCount: 2, lockCount: 1 },
    puzzle: {
      grid: [
        "AABCDEEF",
        "AABCDEEF",
        "AABCDEEF",
        "AABCDGGF",
        "AABCDGGF",
        "HIBCDGGF",
        "HIBCDGGF",
        "HIJCDGGK",
        "HIJCDGGK",
        "HIJCDLLL",
      ],
      clues: { A: [3, 1], B: [5, 2], C: [5, 3], D: [7, 4], E: [1, 5], F: [1, 7], G: [5, 5], H: [6, 0], I: [7, 1], J: [8, 2], K: [8, 7], L: [9, 6] },
      hidden: ["A","D"],
      locks: { J: 6 },
    },
    zones: {
      A: ["Kuş sürülü pastel gök", "pastel sky with flocks of birds", "#f6c6de"],
      B: ["Bulutlar arasında süzülen gökyüzü balinası", "friendly sky whale drifting among clouds", "#a9d8ef"],
      C: ["Çizgili sıcak hava balonu", "striped hot-air balloon", "#f2d16b"],
      D: ["Yel değirmenli küçük uçan ada", "small floating island with a windmill", "#8fc177"],
      E: ["Beyaz tapınaklı, bahçeli ana uçan ada", "main floating island with a white temple and gardens", "#e8d49a"],
      F: ["Ada kenarından dökülen şelale", "waterfall pouring off the island's edge", "#6fb8d8"],
      G: ["Çiçek çayırlı adacık", "flower-meadow islet", "#f2a7c3"],
      H: ["Kristal ağaçlı adacık", "islet with a crystal tree", "#b9a6d8"],
      I: ["Adaları bağlayan halat köprü", "rope bridge linking the islands", "#c9a271"],
      J: ["Bulut denizi", "sea of clouds", "#d6e4f0"],
      L: ["Kulübeli minik adacık", "tiny islet with a red-roofed cottage", "#e0685a"],
      K: ["Bulutların üstünde gökkuşağı", "rainbow arching over the clouds", "#8fd1b8"],
    },
    scene: {
      what: "floating sky islands",
      place: "sky islands",
      structure: "sky island structure",
      bullets: ["connected rope bridges, stairways and island edges", "continuous cloud sea, waterfalls, vines and drifting clouds"],
      light: "one shared lighting source (soft late-morning sun)",
      identity: "sky gradients, cloud tones, island greens, water, stone and soft shadows",
      cross: "A rope bridge may begin in one zone and continue into another; waterfalls, vines, clouds, birds and light rays should flow naturally across the full composition.",
      bounds: "changes in island edges, cloud banks, cliff lines, shadow edges, bridges and soft shifts in ambient lighting",
      style: "airy soft daylight",
      palette: "dreamy pastel",
      readAs: "sky island",
      repeat: "natural",
    },
  },

  {
    id: "jungle-temple", variety: "Çift açılış · Gizli sayı",
    tr: "Orman Tapınağı", artName: "Jungle Temple",
    artGrid: [
      "CCMPPPKK",
      "CCMPPPKK",
      "WHHPPPKK",
      "WHHPPPJJ",
      "WRRSSSJJ",
      "WRRSSSBB",
      "NNVVVVBB",
      "NNLLLLBB",
    ],
    spec: { cols: 8, rows: 10, start: [0, 0], openTech: 3, calm: 0, maxTech: 4, pieceStyle: "big", pieces: [11, 14], effortTarget: 140, t1Max: 0.3, decMin: 11, liveMin: 3, deepMin: 3, cornerMax: 0.35, hiddenCount: 2, lockCount: 1 },
    puzzle: {
      grid: [
        "ABBCCCDE",
        "ABBCCCDE",
        "ABBCCCDE",
        "ABBCCCDE",
        "ABBFFFDE",
        "ABBFFFGG",
        "ABBFFFGG",
        "HHHHHHGG",
        "IIIIIIIJ",
        "KKKKKLLJ",
      ],
      clues: { A: [4, 0], B: [4, 1], C: [1, 5], D: [3, 6], E: [1, 7], F: [4, 4], G: [6, 6], H: [7, 1], I: [8, 2], J: [8, 7], K: [9, 3], L: [9, 6] },
      hidden: ["B","J"],
      locks: { D: 4 },
    },
    zones: {
      C: ["Tukanlı sisli orman tepesi", "misty canopy with toucans", "#7fb98a"],
      M: ["Sarmaşıkta sallanan maymun", "monkey swinging on vines", "#b0824d"],
      P: ["Basamaklı piramit tapınak", "stepped pyramid temple", "#d8c49a"],
      K: ["Uzun ağaçlarda papağanlar", "parrots in tall trees", "#4f9a6a"],
      W: ["Uzun şelale", "tall waterfall", "#6fb8d8"],
      H: ["Yosun kaplı dev taş baş heykeli", "giant moss-covered stone head statue", "#80868c"],
      J: ["Kaya çıkıntısında uzanan jaguar", "jaguar lounging on a rock ledge", "#e0a040"],
      R: ["Sarmaşık kaplı yıkık duvar", "vine-covered ruined wall", "#8fc177"],
      S: ["Meşaleli antik taş merdiven", "ancient stone stairway with torches", "#a0928a"],
      B: ["Turkuaz cenote havuzu", "turquoise cenote pool", "#5fc0b8"],
      N: ["Altın parıltılı mağara girişi", "cave entrance with a golden treasure glow", "#f0a04b"],
      V: ["Orman nehri", "jungle river", "#3f6fb0"],
      L: ["Basamak taşları ve nilüferler", "stepping stones and lily pads", "#b5d86a"],
    },
    scene: {
      what: "ancient jungle temple ruins",
      place: "jungle ruins",
      structure: "jungle ruins structure",
      bullets: ["connected stone stairways, ledges and overgrown walls", "continuous jungle canopy, river, vines and mist"],
      light: "one shared lighting source (sun rays breaking through morning mist)",
      identity: "misty light, jungle greens, weathered stone, water, torch glow and shadows",
      cross: "A stone stairway may begin in one zone and continue into another; vines, roots, the river, mist and sun rays should flow naturally across the full composition.",
      bounds: "changes in stone material, wall corners, ledges, shadow edges, water edges and soft shifts in ambient lighting",
      style: "misty morning light with sun rays",
      palette: "emerald-and-stone with gold accents",
      readAs: "jungle temple",
    },
  },
];
